### ISSUE TITLE
Heketi-cli command failure does not quit the gk-deploy

### ISSUE THREAD

**Issue by MohamedAshiqrh** [gluster/gluster-kubernetes#104]
Any heketi-cli command failure does not call abort instead it just proceeds with other steps.

**Comment by ramkrsna** [comment]
The` set -euo pipefail` should be sufficient for any bash script to abort a command line failure . This #113 should solve this. If you would like debug to see the cause of it,  you could try running the gkdeploy script with 

> $bash -x ./gk-deploy  ..

**Comment by jarrpa** [comment]
I have some concerns with #113 which I've voice in the PR.
