### ISSUE TITLE
Adding device /dev/xxx ... Unable to add device: Failed to get list of pods

### ISSUE THREAD

**Issue by howels** [gluster/gluster-kubernetes#142]
Running this on a working OpenShift install (tried 1.3.1 and 1.5.0-alpha1) and gkdeploy script fails with error 'Failed to get list of pods'  

I have extracted the secret from heketi-service-account and that token's login *is* able to retrieve a list of pods together with labels. I have even granted that user 'cluster-admin' but the message remains.

Using heketi-cli produces that same message after the script is run.

```

Determining heketi service URL ... OK
Creating cluster ... ID: 74f50a43ece6e23cf2828c4c487bcb20
	Creating node openshift3-node-1.lab.com ... ID: a0a6a8be924f5d62499fbe166ddd617b
		Adding device /dev/sdb ... Unable to add device: Failed to get list of pods

	Creating node openshift3-node-2.lab.com ... Unable to create node: Failed to get list of pods

	Creating node openshift3-node-3.lab.com ... Unable to create node: Failed to get list of pods
```

**Comment by howels** [comment]
You are absolutely correct- it's been ignoring the heketi-service-account and using system:serviceaccount:default:default instead.  I found that the following command fixed it:

oc policy add-role-to-user cluster-admin system:serviceaccount:default:default

This doesn't seem correct, I was expecting the heketi-service-account to be used but I may need to pull new sources and try again. I'll check tomorrow.

**Comment by jarrpa** [comment]
@howels See #112 and the related heketi commit linked there. This is a known bug in the gluster-kubernetes project.

**Comment by howels** [comment]
I am using sources from Jan 3rd (commit eea834107d5d9a405a10031b64795548b47b50e2) so it appears that #112 has not fixed the issue, I can clearly see in the console on OpenShift that this service is using system:serviceaccount:default:default as it's service account.

**Comment by jarrpa** [comment]
@howels #112 isn't merged yet.

**Comment by jarrpa** [comment]
@howels #112 is now merged. Please give it a try. :)

**Comment by howels** [comment]
Thanks for the updates, I'll check this tomorrow.

**Comment by obnoxxx** [comment]
btw, @howels , meanwhile #112 is merged.

**Comment by jarrpa** [comment]
@howels Any updates? If we don't hear from you in the next few days we'll close this issue. :)

**Comment by debianmaster** [comment]
any updates ?

**Comment by jarrpa** [comment]
Closing this for now. If someone can reproduce and is willing to troubleshoot, open a new Issue.

**Comment by debianmaster** [comment]
i'm seeing same issue

**Comment by jarrpa** [comment]
@debianmaster Is it this exact issue, and not #250?

**Comment by debianmaster** [comment]
it's same as #250  we can track on that thread

**Comment by VP2405** [comment]
I had the same issue, problems of permissions. Solved it with:

`kubectl create clusterrolebinding gluster-role-binding  --clusterrole=cluster-admin --serviceaccount=default:heketi-service-account`

**Comment by jarrpa** [comment]
@VP2405 Thanks! Do you know if using the `edit` cluster role achieves the same effect?
