### ISSUE TITLE
Add "glusterfs-client" host package to instructions

### ISSUE THREAD

**Issue by etotheipi** [gluster/gluster-kubernetes#160]
PLEASE add `yup/apt-get install glusterfs-client` package to the list of deps to put on each storage host.    That would've saved me many many hours!  

When attempting to run this on an AWS cluster with EBS volumes the first time, I failed at this step due to missing glusters-client on the nodes marked `storagenode=glusterfs`, and then messiness with EBS volumes required lots of cluster&volume destruction and recreation.  

I also used the `modprobe dm_thin_pool` on each node as recommended in another thread, but I'm not sure that was necessary.

**Comment by humblec** [comment]
@etotheipi gluster client packages are not necessary in server nodes. Its only required in nodes where you want to mount and use gluster volumes ie client systems.  `dm_thin_pool` is a required module.

**Comment by etotheipi** [comment]
All I can say is the gk-deploy script failed without it.  The errors had to do with being unable to mount volumes of type "glusterfs".  Unfortunately, I don't have the errors anymore, so I can't copy the exact messages.  But it looked like it had to do with the fact that heketi tries to mount a gluster volume for to store some data for itself.

Keep in mind that this project is targeted (I thought) to be used as PV backing for k8s pods.  That means that any k8s node that will run a pod needing a gluster volume will need this package installed.  In most cases, that's every cluster node.   And it threw me off because I'm not used to having to install packages _on the host_ to get my containers/pods working.

**Comment by jarrpa** [comment]
@etotheipi I agree, I'll see about getting it in.

**Comment by jciniburk** [comment]
Hi,
I may have the similar issue. I have been following installation steps described in https://github.com/gluster/gluster-kubernetes/blob/master/docs/setup-guide.md. But the script run ended with an error. The script created heketi-storage-copy-job-vgbck pod and this pod ended in ContainerCreating state. With command: kubectl describe pods heketi-storage-copy-job-vgbck I retrieved following error:
`Events:
  Type     Reason       Age                 From                 Message
  ----     ------       ----                ----                 -------
  Warning  FailedMount  8m (x1027 over 1d)  kubelet, digicor-n1  Unable to mount volumes for pod "heketi-storage-copy-job-vgbck_default(4d98bd7e-d50e-11e7-b001-000c294fd410)": timeout expired waiting for volumes to attach/mount for pod "default"/"heketi-storage-copy-job-vgbck". list of unattached/unmounted volumes=[heketi-storage]
  Warning  FailedMount  3m (x1601 over 1d)  kubelet, digicor-n1  (combined from similar events): MountVolume.SetUp failed for volume "heketi-storage" : mount failed: mount failed: exit status 32
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/4d98bd7e-d50e-11e7-b001-000c294fd410/volumes/kubernetes.io~glusterfs/heketi-storage --scope -- mount -t glusterfs -o log-level=ERROR,log-file=/var/lib/kubelet/plugins/kubernetes.io/glusterfs/heketi-storage/heketi-storage-copy-job-vgbck-glusterfs.log,backup-volfile-servers=xxx.xxx.xxx.xxx:xxx.xxx.xxx.xxx:xxx.xxx.xxx.xxx xxx.xxx.xxx.xxx:heketidbstorage /var/lib/kubelet/pods/4d98bd7e-d50e-11e7-b001-000c294fd410/volumes/kubernetes.io~glusterfs/heketi-storage
Output: Running scope as unit run-r685bffc097414eec85964aa841531bda.scope.
mount: unknown filesystem type 'glusterfs'

 the following error information was pulled from the glusterfs log to help diagnose this issue: glusterfs: could not open log file for pod: heketi-storage-copy-job-vgbck`

Does this error mean, that I should install glusterfs clients on nodes where are running pods with mounted glusterfs volumes?
Thx

**Comment by jciniburk** [comment]
Sorry, I missed the part in the setup-guide.md about installing the glusterfs-client on the kubernetes nodes and making mount.glusterfs available. It is sufficient to install glusterfs-client on Ubuntu 16.04. Simply run sudo apt-get install glusterfs-client.

**Comment by jarrpa** [comment]
Whew, I thought I had missed something. :)

As the appropriate requirement has been documented both in the tool and in the Setup Guide, closing this issue.
