### ISSUE TITLE
Invalid DeploymentConfig on Openshift

### ISSUE THREAD

**Issue by timbordemann** [gluster/gluster-kubernetes#162]
Im trying to install heketi and glusterfs on an openshift cluster (1.3.3). During the install I get the following error message:

`The DeploymentConfig "heketi" is invalid: spec.template.spec.containers[0].volumeMounts[1].name: Not found: "secret"`

Did anyone get this to work on a recent openshift version? What am I missing?

**Comment by jarrpa** [comment]
Our OpenShift focus has been rather downstream, so it seems we're missing this upstream use case. As I'm traveling right now, can you try removing [these lines](https://github.com/gluster/gluster-kubernetes/blob/master/deploy/ocp-templates/heketi-template.yaml#L89-L90) and seeing if things work then?

**Comment by sterburg** [comment]
I am having the same issue. Removing the "secret" mount part solved the problem. Seems like this part is not needed at all.

**Comment by jarrpa** [comment]
Issue fixed.
