### ISSUE TITLE
gluster/gluster-centos:latest causes gluster pods to crash

### ISSUE THREAD

**Issue by harshal-shah** [gluster/gluster-kubernetes#187]
Hi, 
Since the recent update of gluster/gluster-centos image, I'm unable to have an active daemon set for glusterfs. 
All pods in the dameonset fail with below error: 
```
Mar 04 20:12:54 gke-gfs-k8s-02-default-pool-84f843dd-04bd systemd[1]: Dependency failed for GlusterFS, a clustered file-system server.
Mar 04 20:12:54 gke-gfs-k8s-02-default-pool-84f843dd-04bd systemd[1]: Job glusterd.service/start failed with result 'dependency'.
$ kubectl exec glusterfs-08qwd -- systemctl status glusterd.service
● glusterd.service - GlusterFS, a clustered file-system server
   Loaded: loaded (/usr/lib/systemd/system/glusterd.service; enabled; vendor preset: disabled)
   Active: inactive (dead)
```

I see similar issue reported under heketi here : https://github.com/heketi/heketi/issues/656
I don't see pinning hosts to nodes as the right solution, the daemonset should work like it did before the latest update.

**Comment by harshal-shah** [comment]
For now, I used the gluster-fedora image as a workaround for my daemonset and it worked fine.

**Comment by humblec** [comment]
@harshal-shah can you pull latest container image and give a try again?

**Comment by harshal-shah** [comment]
hi @humblec 
Thanks for your suggestion of disabling rpcbind 
My setup worked after I disabled rpcbind on all nodes. 
Will the new image help irrespective of rpcbind ?

**Comment by MohamedAshiqrh** [comment]
@jarrpa We can close this bug it is fixed in gluster container side.

https://github.com/gluster/gluster-containers/pull/34

**Comment by jarrpa** [comment]
@MohamedAshiqrh Sure thing. If anything comes up, @harshal-shah can comment here or open a new Issue. :)
