### ISSUE TITLE
Error in deployment config heketi 

### ISSUE THREAD

**Issue by SaravanaStorageNetwork** [gluster/gluster-kubernetes#197]
invalid value while creating Deployment config Heketi.

[root@master1 deploy]# oc process heketi | oc create -f  - 
secret "heketi-db-backup" created
service "heketi" created
route "heketi" created
The DeploymentConfig "heketi" is invalid: spec.template.metadata.labels: Invalid value: {"glusterfs":"heketi-pod"}: `selector` does not match template `labels`
[root@master1 deploy]# 

This patch (provided by Ashiq) helped:

--- a/deploy/ocp-templates/heketi-template.yaml
+++ b/deploy/ocp-templates/heketi-template.yaml
@@ -56,7 +56,7 @@ objects:
   spec:
     replicas: 1
     selector:
---      name: heketi
+++      glusterfs: heketi-pod

**Comment by MohamedAshiqrh** [comment]
@jarrpa This is caused due the changes with the PR https://github.com/gluster/gluster-kubernetes/pull/191.

**Comment by MohamedAshiqrh** [comment]
@humblec @obnoxxx We need CI soon.....

**Comment by obnoxxx** [comment]
@MohamedAshiqrh Agreed. I enabled travis on the repo. And see PRs #193 and #194 for a start in the code.

**Comment by mr-falken** [comment]
Even with the patch suggested I still get that error: do we need to modify the kube-templates/heketi-deployment.yaml file as well ?

**Comment by humblec** [comment]
@jarrpa @obnoxxx looks to me that, we need to discard the change introduced in #191  .

**Comment by obnoxxx** [comment]
@humblec yeah. maybe not discard, but fix. Iirc, @jarrpa had a fix-patch pending. For the time being, does locally reverting this patch (of #191) help?

**Comment by humblec** [comment]
@mr-falken Can you please remove the changes in #191 in your local setup and try to deploy this project?

**Comment by mr-falken** [comment]
@humblec I can confirm that the patch suggested by @SaravanaStorageNetwork works, haven't tried from a "clean" run though: "oc edit template heketi-template" and applying the patch did the job :)
In next few days I'll try to start a brand new openshift cluster with glusterfs dyn provisioning from scratch (without #191) and give you some feedback

**Comment by obnoxxx** [comment]
@mr-falken, thanks for confirming. This is essentially reverting the patch or PR #191.

As I said, José indented to provide a fix patch anyways since he had already spotted the problem. I don't see a corresponding PR yet, though. So please stay tuned... :-)
