### ISSUE TITLE
problem with quickstart

### ISSUE THREAD

**Issue by obnoxxx** [gluster/gluster-kubernetes#202]
Following the quickstart, when I do 'export KUBECONFIG="/etc/kubernetes/admin.conf"' as documented, gk-deploy errors out with 'Namespace 'admin@kubernetes' not found'.

**Comment by humblec** [comment]
@obnoxxx I export user's kubeconfig always. Never tried admin's config. @jarrpa Did the documented way works for you ?

**Comment by humblec** [comment]
@jarrpa confirm this worked for him. In that case, need to check the content in admin's config in @obnoxxx's setup.

**Comment by jarrpa** [comment]
@obnoxxx @humblec Just verified that the Quickstart instructions as they exist don't work for me either. Odd. I would've thought that you'd need some form of auth to do admin operations in Kubernetes...

Regardless, at the moment providing no value in KUBECONFIG seems to be what works in the Quickstart scenario. I'll edit that accordingly.
