### ISSUE TITLE
Installation on Atomic Host

### ISSUE THREAD

**Issue by sterburg** [gluster/gluster-kubernetes#211]
Gluster Container Native Storage installation currently requires a Non-Container Native OS because it requires the installation of the heketi-cli rpm.

I've noticed the heketi-cli tool is packaged with the heketi/heketi docker-image used by the heketi-deployer pod.
And creating a bash alias like this actually works: 
`/bin/kubectl -n storage exec -t -i $POD_NAME -- heketi-cli $*`

It would be nice if we can support installing Gluster CNS storage on a Container-Native OS like Atomic Host the Container Native way (running the deployer/installer inside a docker-image).

Using `atomic install` would also be a nice alternative way.

FYI, My use-case:
when using OpenShift / Kubernetes i never have to manually use heketi-cli (create volumes). Only during installation (load topology).

**Comment by jarrpa** [comment]
This has been addressed in the latest versions of gk-deploy.
