### ISSUE TITLE
Wait for a valid endpoint value in svc describe output

### ISSUE THREAD

**Issue by raghavendra-talur** [gluster/gluster-kubernetes#229]
When oc describe svc/heketi is performed, we can have output as shown below

```
Name:                   heketi
Namespace:              storage-project
Labels:                 glusterfs=heketi-service
                        template=heketi
Selector:               glusterfs=heketi-pod
Type:                   ClusterIP
IP:                     172.30.28.113
Port:                   heketi  8080/TCP
Endpoints:
Session Affinity:       None
No events.
```

Here value for Endpoints: is "" and not "\<none\>", we need to wait until a valid string appears here before proceeding to confirm deployment of heketi.

**Comment by jarrpa** [comment]
@raghavendra-talur @MohamedAshiqrh Regarding this, I'd like to have a brief discussion: Can we get rid of using the route for the oc deployment? The Endpoint from the Service seems to be just as valid in OpenShift as it is in Kubernetes, and would cleanup the code significantly.
