### ISSUE TITLE
Failing w/  Unable to create node:   on openshift (running topology adds 1st node, fails subsequent nodes)

### ISSUE THREAD

**Issue by debianmaster** [gluster/gluster-kubernetes#250]
Unable to deploy on openshift cluster.    
I'm running with cluster-admin priv and also privileged privileged scc
running topology adds 1st node, fails subsequent nodes

```sh
[Y]es, [N]o? [Default: Y]: y
Using OpenShift CLI.
NAME       STATUS    AGE
xfc-prod   Active    5h
Using namespace "xfc-prod".
Checking that heketi pod is not running ... OK
template "deploy-heketi" created
serviceaccount "heketi-service-account" created
template "heketi" created
template "glusterfs" created
node "master1.c.silver-pen-163919.internal" labeled
node "master2.c.silver-pen-163919.internal" labeled
node "master3.c.silver-pen-163919.internal" labeled
daemonset "glusterfs" created
Waiting for GlusterFS pods to start ... OK
service "deploy-heketi" created
route "deploy-heketi" created
deploymentconfig "deploy-heketi" created
Waiting for deploy-heketi pod to start ... OK
Creating cluster ... ID: b7f7e7f782fd78039850508d60d84464
Creating node master1.c.silver-pen-163919.internal ... ID: bf5798bc557d8db30a9248afc736d3e2
Adding device /dev/sdb ... OK
Creating node master2.c.silver-pen-163919.internal ... Unable to create node: Unable to execute command on glusterfs-kk4ex: peer probe: failed: Probe returned with Transport endpoint is not connected
Creating node master3.c.silver-pen-163919.internal ... Unable to create node: Unable to execute command on glusterfs-kk4ex: peer probe: failed: Probe returned with Transport endpoint is not connected
Error loading the cluster topology.
Please check the failed node or device and rerun this script using the --load option.
```

**Comment by MohamedAshiqrh** [comment]
@debianmaster Did you mention -g in the gk-deploy command? also can you paste the topology file here? Is all the required ports open?

Looks like something wrong in topology file. 

master2.c.silver-pen-163919.internal is second node and pod name is glusterfs-kk4ex.
master3.c.silver-pen-163919.internal is third node and pod name is glusterfs-kk4ex.

Both pods are same. This looks fishy.

**Comment by debianmaster** [comment]
```json
{
  "clusters": [
    {
      "nodes": [
        {
          "node": {
            "hostnames": {
              "manage": [
                "master1.c.silver-pen-163919.internal"
              ],
              "storage": [
                "10.240.0.10"
              ]
            },
            "zone": 1
          },
          "devices": [
            "/dev/sdb"
          ]
        },
        {
          "node": {
            "hostnames": {
              "manage": [
                "master2.c.silver-pen-163919.internal"
              ],
              "storage": [
                "10.240.0.11"
              ]
            },
            "zone": 1
          },
          "devices": [
            "/dev/sdb"
          ]
        },
        {
          "node": {
            "hostnames": {
              "manage": [
                "master3.c.silver-pen-163919.internal"
              ],
              "storage": [
                "10.240.0.12"
              ]
            },
            "zone": 1
          },
          "devices": [
            "/dev/sdb"
          ]
        }
      ]
    }
  ]
}
```
topology seems ok to me.    i did see pods having same name but topology has diff names.   does *zone*  needs to be different?

**Comment by debianmaster** [comment]
tried changing zone to diff values still same issue

**Comment by jarrpa** [comment]
@debianmaster Looks like there's a networking issue somewhere. Can you `oc rsh` into one of the gluster pods and see if you can ping the other nodes?

**Comment by debianmaster** [comment]
@jarrpa  i'm able to rsh to daemon set pod and ping other nodes in cluster
any other pointers?

**Comment by debianmaster** [comment]
[heketi] ERROR 2017/04/15 03:43:02 /src/github.com/heketi/heketi/apps/glusterfs/volume_entry_allocate.go:38: Minimum brick size limit reached.  Out of space.
[asynchttp] INFO 2017/04/15 03:43:02 Completed job e436b1f75ff1f8f567b9272217782ceb in 12.281471ms
[heketi] ERROR 2017/04/15 03:43:02 /src/github.com/heketi/heketi/apps/glusterfs/app_volume.go:148: Failed to create volume: No space
[negroni] Started GET /queue/e436b1f75ff1f8f567b9272217782ceb
[negroni] Completed 500 Internal Server Error in 115.658µs



i'm spending crazy time on this!    is there a updated video for deploying on k8s?   video seems to be old

**Comment by jarrpa** [comment]
@debianmaster The No Space error is something which we have gotten some criticism about but have not come up with a good solution for. It can stand for a number of error scenarios that are difficult to isolate at this time.

Two things to consider:
1. Did you go through the pre-req steps to open all the required ports for the GlusterFS pods?
2. Are the devices you're adding clean (no filesystem AND not marked as LVM PVs) and at least 1 GB in size?

If these are true, then I suggest starting over from scratch, get to the error state, then check (and post if needed) what look like relevant portions of the `oc logs` for the deploy-heketi pod and the one GlusterFS pod that is listed in the error output of gk-deploy.

**Comment by SaravanaPunith** [comment]
I am also facing this No space error same as @debianmaster. Logs while executing gk-deploy: 

[root@m1 deploy]# ./gk-deploy -c oc -g  topology.json  
Welcome to the deployment tool for GlusterFS on Kubernetes and OpenShift.

Before getting started, this script has some requirements of the execution
environment and of the container platform that you should verify.

The client machine that will run this script must have:
 * Administrative access to an existing Kubernetes or OpenShift cluster
 * Access to a python interpreter 'python'
 * Access to the heketi client 'heketi-cli'

Each of the nodes that will host GlusterFS must also have appropriate firewall
rules for the required GlusterFS ports:
 * 2222  - sshd (if running GlusterFS in a pod)
 * 24007 - GlusterFS Daemon
 * 24008 - GlusterFS Management
 * 49152 to 49251 - Each brick for every volume on the host requires its own
   port. For every new brick, one new port will be used starting at 49152. We
   recommend a default range of 49152-49251 on each host, though you can adjust
   this to fit your needs.

In addition, for an OpenShift deployment you must:
 * Have 'cluster_admin' role on the administrative account doing the deployment
 * Add the 'default' and 'router' Service Accounts to the 'privileged' SCC
 * Have a router deployed that is configured to allow apps to access services
   running in the cluster

Do you wish to proceed with deployment?

[Y]es, [N]o? [Default: Y]: Y
Using OpenShift CLI.
NAME           STATUS    AGE
glusterstore   Active    9h
Using namespace "glusterstore".
Checking that heketi pod is not running ... OK
template "deploy-heketi" created
serviceaccount "heketi-service-account" created
template "heketi" created
template "glusterfs" created
node "m1" labeled
node "c1" labeled
node "c2" labeled
daemonset "glusterfs" created
Waiting for GlusterFS pods to start ... OK
service "deploy-heketi" created
route "deploy-heketi" created
deploymentconfig "deploy-heketi" created
Waiting for deploy-heketi pod to start ... OK
Creating cluster ... ID: fc74e4ee3cd42c127b3d45adbdc1f8aa
Creating node m1 ... ID: 8ac07a8c8dbbdd392c1f8dab81dd4395
Adding device /dev/vdb ... OK
Creating node c1 ... ID: eccf5f908572dff94886e9b7d505efb2
Adding device /dev/vdb ... OK
Creating node c2 ... ID: 9a4953c772e57555d4dbb14c23609fcf
Adding device /dev/vdb ... OK
heketi topology loaded.
Error: No space
Failed on setup openshift heketi storage

**Comment by jarrpa** [comment]
@SaravanaPunith Your error is different from @debianmaster's, please open a new Issue.

**Comment by debianmaster** [comment]
running this command on all nodes fixed issue `sudo iptables -I INPUT -p all -j ACCEPT
`

**Comment by jarrpa** [comment]
@debianmaster oh... I suppose that's a valid question: did you open the requisite firewall ports on all the nodes that would be running GlusterFS pods?

**Comment by debianmaster** [comment]
@jarrpa  i opened on cloud level, but looks like i need to open at host level too.    not a networking pro :P    thanks for the quick help.   everything seems to work now!

**Comment by jarrpa** [comment]
@debianmaster Happy to hear! :D Best of luck.
