### ISSUE TITLE
Error: No space while executing gk-deploy

### ISSUE THREAD

**Issue by SaravanaPunith** [gluster/gluster-kubernetes#253]
I am facing this "No space error".
Logs while executing gk-deploy:

All the vdb devices are freshly added using virt-manager and they are raw devices each of 4GB size.

===================================
```
[root@m1 deploy]# ./gk-deploy -c oc -g topology.json
Welcome to the deployment tool for GlusterFS on Kubernetes and OpenShift.

Before getting started, this script has some requirements of the execution
environment and of the container platform that you should verify.

The client machine that will run this script must have:

Administrative access to an existing Kubernetes or OpenShift cluster
Access to a python interpreter 'python'
Access to the heketi client 'heketi-cli'
Each of the nodes that will host GlusterFS must also have appropriate firewall
rules for the required GlusterFS ports:
2222 - sshd (if running GlusterFS in a pod)
24007 - GlusterFS Daemon
24008 - GlusterFS Management
49152 to 49251 - Each brick for every volume on the host requires its own
port. For every new brick, one new port will be used starting at 49152. We
recommend a default range of 49152-49251 on each host, though you can adjust
this to fit your needs.
In addition, for an OpenShift deployment you must:
Have 'cluster_admin' role on the administrative account doing the deployment
Add the 'default' and 'router' Service Accounts to the 'privileged' SCC
Have a router deployed that is configured to allow apps to access services
running in the cluster
Do you wish to proceed with deployment?
[Y]es, [N]o? [Default: Y]: Y
Using OpenShift CLI.
NAME STATUS AGE
glusterstore Active 9h
Using namespace "glusterstore".
Checking that heketi pod is not running ... OK
template "deploy-heketi" created
serviceaccount "heketi-service-account" created
template "heketi" created
template "glusterfs" created
node "m1" labeled
node "c1" labeled
node "c2" labeled
daemonset "glusterfs" created
Waiting for GlusterFS pods to start ... OK
service "deploy-heketi" created
route "deploy-heketi" created
deploymentconfig "deploy-heketi" created
Waiting for deploy-heketi pod to start ... OK
Creating cluster ... ID: fc74e4ee3cd42c127b3d45adbdc1f8aa
Creating node m1 ... ID: 8ac07a8c8dbbdd392c1f8dab81dd4395
Adding device /dev/vdb ... OK
Creating node c1 ... ID: eccf5f908572dff94886e9b7d505efb2
Adding device /dev/vdb ... OK
Creating node c2 ... ID: 9a4953c772e57555d4dbb14c23609fcf
Adding device /dev/vdb ... OK
heketi topology loaded.
Error: No space
Failed on setup openshift heketi storage

```
===================================

**Comment by jarrpa** [comment]
@SaravanaPunith Could you also paste your topology file?

**Comment by SaravanaPunith** [comment]
```
[root@m1 deploy]# cat topology.json
{
  "clusters": [
    {
      "nodes": [
        {
          "node": {
            "hostnames": {
              "manage": [
                "m1"
              ],
              "storage": [
                "192.168.122.152"
              ]
            },
            "zone": 1
          },
          "devices": [
            "/dev/vdb"
          ]
        },
	{
          "node": {
            "hostnames": {
              "manage": [
                "c1"
              ],
              "storage": [
                "192.168.122.144"
              ]
            },
            "zone": 1
          },
          "devices": [
            "/dev/vdb"
          ]
	},
        {
          "node": {
            "hostnames": {
              "manage": [
                "c2"
              ],
              "storage": [
                "192.168.122.210"
              ]
            },
            "zone": 1
          },
          "devices": [
            "/dev/vdb"
          ]
        }
      ]
    }
  ]
}

```

**Comment by jarrpa** [comment]
@SaravanaPunith Thanks. I'm not seeing anything to point to cause immediately. @humblec can you take a look?

**Comment by SaravanaPunith** [comment]
some logs from node, while running gk-deploy:

Apr 17 14:33:19 c1 dockerd-current[1164]: [negroni] Started GET /clusters
Apr 17 14:33:19 c1 dockerd-current[1164]: [negroni] Completed 200 OK in 81.467µs
Apr 17 14:33:19 c1 dockerd-current[1164]: [negroni] Started GET /clusters/fc74e4ee3cd42c127b3d45adbdc1f8aa
Apr 17 14:33:19 c1 dockerd-current[1164]: [negroni] Completed 200 OK in 211.72µs
Apr 17 14:33:19 c1 dockerd-current[1164]: [negroni] Started GET /nodes/8ac07a8c8dbbdd392c1f8dab81dd4395
Apr 17 14:33:19 c1 dockerd-current[1164]: [negroni] Completed 200 OK in 219.326µs
Apr 17 14:33:19 c1 dockerd-current[1164]: [negroni] Started GET /nodes/9a4953c772e57555d4dbb14c23609fcf
Apr 17 14:33:19 c1 dockerd-current[1164]: [negroni] Completed 200 OK in 318.617µs
Apr 17 14:33:19 c1 dockerd-current[1164]: [negroni] Started GET /nodes/eccf5f908572dff94886e9b7d505efb2
Apr 17 14:33:19 c1 dockerd-current[1164]: [negroni] Completed 200 OK in 235.497µs
Apr 17 14:33:19 c1 dockerd-current[1164]: [negroni] Started GET /clusters/fc74e4ee3cd42c127b3d45adbdc1f8aa
Apr 17 14:33:19 c1 dockerd-current[1164]: [negroni] Completed 200 OK in 144.224µs
Apr 17 14:33:19 c1 dockerd-current[1164]: [negroni] Started GET /clusters/fc74e4ee3cd42c127b3d45adbdc1f8aa
Apr 17 14:33:19 c1 dockerd-current[1164]: [negroni] Completed 200 OK in 145.059µs
Apr 17 14:33:19 c1 dockerd-current[1164]: [negroni] Started GET /clusters/fc74e4ee3cd42c127b3d45adbdc1f8aa
Apr 17 14:33:19 c1 dockerd-current[1164]: [negroni] Completed 200 OK in 136.018µs
Apr 17 14:33:19 c1 dockerd-current[1164]: [negroni] Started GET /clusters
Apr 17 14:33:19 c1 dockerd-current[1164]: [negroni] Completed 200 OK in 62.476µs
Apr 17 14:33:19 c1 dockerd-current[1164]: [negroni] Started GET /clusters/fc74e4ee3cd42c127b3d45adbdc1f8aa
Apr 17 14:33:19 c1 dockerd-current[1164]: [negroni] Completed 200 OK in 175.811µs
Apr 17 14:33:19 c1 dockerd-current[1164]: [negroni] Started POST /volumes
Apr 17 14:33:19 c1 dockerd-current[1164]: [negroni] Completed 202 Accepted in 70.729µs
Apr 17 14:33:19 c1 dockerd-current[1164]: [asynchttp] INFO 2017/04/17 18:33:19 Started job 363bc6ae41bbcbe5037a727d77268fc3
Apr 17 14:33:19 c1 dockerd-current[1164]: [heketi] INFO 2017/04/17 18:33:19 Creating volume 3af06af7544b3cc173e8ea615311e3a6
Apr 17 14:33:19 c1 dockerd-current[1164]: [heketi] INFO 2017/04/17 18:33:19 brick_num: 0
Apr 17 14:33:19 c1 dockerd-current[1164]: [negroni] Started GET /queue/363bc6ae41bbcbe5037a727d77268fc3
Apr 17 14:33:19 c1 dockerd-current[1164]: [negroni] Completed 200 OK in 22.258µs
Apr 17 14:33:19 c1 dockerd-current[1164]: [heketi] INFO 2017/04/17 18:33:19 brick_num: 0
Apr 17 14:33:19 c1 dockerd-current[1164]: [heketi] INFO 2017/04/17 18:33:19 brick_num: 0
Apr 17 14:33:19 c1 dockerd-current[1164]: [heketi] INFO 2017/04/17 18:33:19 brick_num: 0
Apr 17 14:33:19 c1 dockerd-current[1164]: [heketi] ERROR 2017/04/17 18:33:19 /src/github.com/heketi/heketi/apps/glusterfs/app_volume.go:148: Failed to create volume: No space
..
Apr 17 14:33:22 c1 systemd[1]: Scope libcontainer-11229-systemd-test-default-dependencies.scope has no PIDs. Refusing.
Apr 17 14:33:22 c1 dockerd-current[1164]: time="2017-04-17T14:33:22.162669864-04:00" level=warning msg="containerd: unable to save 2c9117e1bc89df452f85bfe205c0452f2a89744fd9d0991b076afcecd1729f36:53f0d48e58acc040c5c4849a964aa3275df06bd0c4f1890cf162c81057edd378 starttime: open /proc/11240/stat: no such file or directory"
Apr 17 14:33:22 c1 dockerd-current[1164]: time="2017-04-17T14:33:22.162991184-04:00" level=info msg="containerd: 2c9117e1bc89df452f85bfe205c0452f2a89744fd9d0991b076afcecd1729f36:53f0d48e58acc040c5c4849a964aa3275df06bd0c4f1890cf162c81057edd378 (pid 11240) has become an orphan, killing it"

**Comment by MohamedAshiqrh** [comment]
@jarrpa He is using old heketi-client-3.0.0-1 Which makes use of 4 GB for the db volume AFAIK.

**Comment by SaravanaPunith** [comment]
Thanks to @MohamedAshiqrh , issue is fixed as below:


// heketi version is old
[root@m1 deploy]# rpm -qa | grep heketi
heketi-client-3.0.0-1.el7.x86_64
heketi-3.0.0-1.el7.x86_64
heketi-templates-3.0.0-1.el7.x86_64


downloaded heketi-client-v4.0.0.linux.amd64.tar.gz from https://github.com/heketi/heketi/releases.

// Replaced heketi-cli as below:
cp bin/heketi-cli  /usr/bin/heketi-cli/

Now, all is well :+1:

**Comment by SaravanaPunith** [comment]
Time to update heketi in official Centos release ?

```
# yum search heketi 
===================================================== N/S matched: heketi =====================================================
heketi-client.x86_64 : Command line client for Heketi
heketi-templates.x86_64 : Heketi and GlusterFS templates for Heketi
python-heketi.x86_64 : Python libraries for Heketi
heketi.x86_64 : RESTful based volume management framework for GlusterFS
Name and summary matches only, use "search all" for everything.

[root@m1 deploy]# yum info heketi-client.x86_64
Loaded plugins: fastestmirror
Repository centos-openshift-origin is listed more than once in the configuration
Repository centos-openshift-origin-testing is listed more than once in the configuration
Repository centos-openshift-origin-debuginfo is listed more than once in the configuration
Repository centos-openshift-origin-source is listed more than once in the configuration
Loading mirror speeds from cached hostfile
 * base: centos.excellmedia.net
 * epel: epel.mirror.angkasa.id
 * extras: centos.excellmedia.net
 * updates: centos.excellmedia.net
Installed Packages
Name        : heketi-client
Arch        : x86_64
Version     : 3.0.0
Release     : 1.el7
Size        : 17 M
Repo        : installed
From repo   : epel
Summary     : Command line client for Heketi
URL         : https://github.com/heketi/heketi
License     : ASL 2.0
Description : Command line client for Heketi
            : 
            : Command line program to interact with Heketi
```

**Comment by MohamedAshiqrh** [comment]
@SaravanaPunith you can create a Issue in heketi repo to build a new rpm for centos.

**Comment by 4admin2root** [comment]
the same issue

**Comment by MohamedAshiqrh** [comment]
heketidbstorage volume takes 2 GB now but in the build 3.0.0-1 it takes 32GB.

**Comment by jarrpa** [comment]
Thanks @MohamedAshiqrh! Closing this issue. :)
