### ISSUE TITLE
gk-deploy got the wrong namespace name

### ISSUE THREAD

**Issue by chuenlye** [gluster/gluster-kubernetes#254]
gk-deploy got the wrong namespace name when context name was not the same with the namespace name.

```
Usage:
  kubectl config set-context NAME [--cluster=cluster_nickname] [--user=user_nickname] [--namespace=namespace] [options]
```

`kubectl config current-context` will output the context name, but 
context name may not the same with namespace name.

**Comment by jarrpa** [comment]
Resolved by #264.
