### ISSUE TITLE
What's different between deploy-heketi  and heketi-deployment?

### ISSUE THREAD

**Issue by leo200149** [gluster/gluster-kubernetes#262]
I know the shell `gk-deploy`'s step as below:

1. create `heketi-service-account`.
2. all nodes add label `storagenode=glusterfs` and create `daemonset glusterfs`.
3. create `deploy-heketi` and service.
4. `deploy-heketi`  load `topology.json` (add gluster nodes and devices)
5.  run `setup-openshift-heketi-storage` to create `heketi-storage` and `heketi-storage.json`
6.  use `heketi-storage.json` to create endpoint,`heketi-storage-copy-job`(copy `heketi-storage` for `heketi-deployment`)
7. delete all `deploy-heketi`'s resource.
8. create `heketi-deployment` and service.
9. install complete and test.

I don't know why need to do step 5~8, and I can't find the explanation in the document.

I want to know:
What's different between `deploy-heketi`  and `heketi-deployment`? 
Why need to do that?

Thanks

**Comment by jarrpa** [comment]
For clarity, we are distinguishing between `deploy-heketi` and the production `heketi` pod. :)

I will start by saying that, yes, this is weird and somewhat obscure. Ultimately, this is all technical acrobatics to work around the default limitations of Kubernetes' storage. heketi, the service, maintains a database of metadata about the GlusterFS clusters, nodes, volumes, and storage devices it manages. By default, as a pod this database exists in ephemeral storage, thus if the pod goes down or is restarted the database would be lost and heketi would not be able to recreate it.

The current solution we've implemented is to create a heketi pod for deploying a heketi pod, called `deploy-heketi`. This pod has an initial database that stores data for the initial GlusterFS cluster we configure with the `topology.json` file, but this is in volatile storage. The `setup-openshift-heketi-storage` command generates the JSON for a job to copy the metadata database into a newly-created GlusterFS volume specifically for hosting said database. The `heketi` pod, then, is configured to mount this GlusterFS volume and access the database from this volume. Thus, the database is now in persistent storage.

Whew... that was longer than anticipated. Let me know if that helps. :) If it does, please suggest where would be a convenient place to document that.

**Comment by leo200149** [comment]
Maybe you can put this comment after `Setup Guide`'s `Deployment Overview`?
`Deployment Overview` step 4,5,6 can add explanation to talk why should need to do that.

Just a suggestion :)
Thanks for your explanation.
