### ISSUE TITLE
Use namespace for heketi/gluster resources

### ISSUE THREAD

**Issue by webwurst** [gluster/gluster-kubernetes#27]
If all resources of Heketi and GlusterFS reside in one namespace, it might be easier to filter for them on metrics or logging.

Also to stop and remove all resources gracefully you then can just call:
```
kubectl delete namespace glusterfs
```

**Comment by jarrpa** [comment]
I provided a mechanism for specifying namespaces in #28, but I did not change the abort() function to delete all items in the namespace. I can see a scenario where users would want to deploy to a non-default namespace that would contain other resources. However, they can still go ahead and `delete namespace` if they so wish to shortcut things.
