### ISSUE TITLE
Kubernetes topology load attempts to execute on the same pod

### ISSUE THREAD

**Issue by AlterEgo7** [gluster/gluster-kubernetes#276]
I am attempting to deploy GlusterFS over a Kubernetes cluster. The Kubernetes cluster is already deployed using [kubespray](https://github.com/kubernetes-incubator/kubespray) (aka kargo), with the following configuration:
* gluster1 : master
* gluster2: node
* gluster3: node
* gluster4: node

**Kubernetes Version:** 1.6.6
**OS:** Ubuntu 16.04 on Vagrant
**gluster-kubernetes Version:** 1.1
**Heketi client Version:** 4.0

The 3 Kubernetes nodes are to be the glusterfs nodes as well. I follow the instruction found here: [https://github.com/heketi/heketi/wiki/Kubernetes-Integration](https://github.com/heketi/heketi/wiki/Kubernetes-Integration). The problem also manifests if I use the gk-deploy script.

The commands that I use are the following, within the kube-templates folder:
```
kubectl create -f heketi-service-account.yaml
kubectl label node gluster{2..4} storagenode=glusterfs
kubectl create -f glusterfs-daemonset.yaml
kubectl create -f deploy-heketi-deployment.yaml
kubectl port-forward deploy-heketi-3389103616-jp15s :8080
export HEKETI_CLI_SERVER=http://localhost:37823
```
The topology load command fails with the following error:

```
$ heketi-client/bin/heketi-cli topology load --json=topology.json
Handling connection for 37823
Creating cluster ... ID: 6c2dabb7514bfb6a1c683e89bdec444b
	Creating node gluster2 ... ID: 3049af98f1b18e426e1be9f144020e0f
		Adding device /dev/sdc ... OK
	Creating node gluster3 ... Unable to create node: Unable to execute command on glusterfs-nhk3d:
	Creating node gluster4 ... Unable to create node: Unable to execute command on glusterfs-nhk3d:
```

The kubernetes executor of heketi attempts to execute the commands on the same pod regardless of the hostname and IPs given in the topology.json file.

For further reference:

The output of `kubectl get pod` is:

```
NAME                             READY     STATUS    RESTARTS   AGE       IP               NODE
deploy-heketi-3389103616-jp15s   1/1       Running   0          4m        10.233.89.2      gluster3
glusterfs-5znsj                  1/1       Running   0          5m        192.168.62.103   gluster3
glusterfs-nhk3d                  1/1       Running   0          5m        192.168.62.102   gluster2
glusterfs-qwnzf                  1/1       Running   0          5m        192.168.62.104   gluster4
```

The output of `kubectl get node` is:
```
NAME       STATUS                     AGE       VERSION                 EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION
gluster1   Ready,SchedulingDisabled   14h       v1.6.6+coreos.0-dirty   <none>        Ubuntu 16.04.2 LTS   4.4.0-79-generic
gluster2   Ready                      14h       v1.6.6+coreos.0-dirty   <none>        Ubuntu 16.04.2 LTS   4.4.0-79-generic
gluster3   Ready                      14h       v1.6.6+coreos.0-dirty   <none>        Ubuntu 16.04.2 LTS   4.4.0-79-generic
gluster4   Ready                      14h       v1.6.6+coreos.0-dirty   <none>        Ubuntu 16.04.2 LTS   4.4.0-79-generic
```

I also attach my Vagrantfile and topology.json.

[Vagrantfile.txt](https://github.com/gluster/gluster-kubernetes/files/1089866/Vagrantfile.txt)

[topology.json.txt](https://github.com/gluster/gluster-kubernetes/files/1089868/topology.json.txt)

**Comment by dcorn** [comment]
Does gluster on node gluster2 crash after Adding device /dev/sdc ... OK?

I am having the exact same issue.  After the adding device it crashes, the errors in the logs are as follows.

`Creating cluster ... ID: 51a2149f6080c232112e98c0f3ebe763
Creating node 872218-knode02 ... ID: 37a2ef29f5acbe801a61a6b6243bc643
Adding device /dev/sdb ... OK
Creating node 872220-knode03 ... Unable to create node: Unable to execute command on glusterfs-knp6r:
Creating node 874746-knode04 ... Unable to create node: Unable to execute command on glusterfs-knp6r:
Error loading the cluster topology.
Please check the failed node or device and rerun this script using the --load option.`

Gluster log on crashed node

`[2017-06-22 16:27:13.309047] E [MSGID: 101032] [store.c:433:gf_store_handle_retrieve] 0-: Path corresponding to /var/lib/glusterd/glusterd.info. [No such file or directory]
[2017-06-22 16:27:13.309135] E [MSGID: 101032] [store.c:433:gf_store_handle_retrieve] 0-: Path corresponding to /var/lib/glusterd/glusterd.info. [No such file or directory]
[2017-06-22 16:27:13.309159] I [MSGID: 106514] [glusterd-store.c:2219:glusterd_restore_op_version] 0-management: Detected new install. Setting op-version to maximum : 31000
[2017-06-22 16:27:13.310626] I [MSGID: 106498] [glusterd-handler.c:3669:glusterd_friend_add_from_peerinfo] 0-management: connect returned 0
[2017-06-22 16:27:13.310717] W [MSGID: 106062] [glusterd-handler.c:3466:glusterd_transport_inet_options_build] 0-glusterd: Failed to get tcp-user-timeout
[2017-06-22 16:27:13.310751] I [rpc-clnt.c:1059:rpc_clnt_connection_init] 0-management: setting frame-timeout to 600
pending frames:
patchset: git://git.gluster.org/glusterfs.git
signal received: 11`

on heketi I get the following

`[kubeexec] ERROR 2017/06/22 15:36:48 /src/github.com/heketi/heketi/executors/kubeexec/kubeexec.go:247: Failed to run command [gluster peer probe 10.10.150.144] on glusterfs-19zpf: Err[command terminated with exit code 1]: Stdout [Connection failed. Please check if gluster daemon is operational.`


 `[kubeexec] ERROR 2017/06/22 15:36:49 /src/github.com/heketi/heketi/executors/kubeexec/kubeexec.go:247: Failed to run command [gluster peer probe 10.10.150.151] on glusterfs-19zpf: Err[command terminated with exit code 1]: Stdout [Connection failed. Please check if gluster daemon is operational.`

**Comment by AlterEgo7** [comment]
@dcorn yes shortly after, I get an error on the pod where heketi added the device. However, I don't have logs, kubectl logs does not return anything.

**Comment by dcorn** [comment]
Same here.  check /var/log/gluster/glusterd.log on the node. If that does not work you will need to attach to the container.  I have been dealing with this for 2 days now and im clueless to the solution.

**Comment by dcorn** [comment]
@AlterEgo7 By chance did you use kargo/kubespray to deploy your kube stack?

**Comment by dcorn** [comment]
Trying to setup Glusterfs on the nodes outside of Kubernetes yield the same results.   I get segfaults when trying to probe a peer.

**Comment by AlterEgo7** [comment]
@dcorn I use flannel as the network interface. I have also tested with calico and have the same results.

**Comment by AlterEgo7** [comment]
This relates to [https://github.com/kubernetes-incubator/kubespray/issues/1196](https://github.com/kubernetes-incubator/kubespray/issues/1196). I will post solution there.

**Comment by jarrpa** [comment]
Glad this was properly troubleshot! :) Apologies for the silence, I was just BAFFLED... at least I had the right idea that it was a network-thing.
