### ISSUE TITLE
Hello-world application docs needs a few updates

### ISSUE THREAD

**Issue by dougbtv** [gluster/gluster-kubernetes#292]
These are mostly nits, but as I ran through my setup, I found a couple issues with docs (happy to submit a PR for them) for the hello world app.

https://github.com/gluster/gluster-kubernetes/blob/master/docs/examples/hello_world/README.md#create-a-storageclass-for-our-glusterfs-dynamic-provisioner

1. In the storageclass yaml, there's a space in front of ` parameters:` which causes kube to reject it if you copy-paste it.

2. In the storageclass yaml, at least under Kube 1.7, kube rejects adding the storageclass with the `endpoint` parameter. 

3. It may be worth pointing out that for the `resturl` you should be able to use the kube DNS entry for the heketi svc.

Regardless, hello-world application document was helpful in validating my setup. Appreciated the document quite a bit, well done.

**Comment by obnoxxx** [comment]
Thanks for your feed-back @dougbtv !
Happy to review PRs from you if you are willing to fix the issues found!

Note that the `vagrant/demo` essentially has the steps from the quicktart and hello-world guides as runnable demos, and the `tests/complex` has them as a selftest suite (runnable in a single command). So at least the selftest one should have been kept up-to date. Feel free to use that as a reference.

**Comment by jarrpa** [comment]
@dougbtv Oh! Sorry I missed this one! :( Indeed, thank you for you comments. I would also encourage you to submit a PR to update the documentation, that woul dhelp us out. :)

**Comment by dougbtv** [comment]
Thanks guys -- I've submitted a PR on this one, really short update.

Also note that the extra space got fixed in 65b4b6d2917f176bdc1cb389e37843b73d9e9aa7

Thanks again for the really great docs generally, I have appreciated it.
