### ISSUE TITLE
Cant add device to cluster

### ISSUE THREAD

**Issue by felixPG** [gluster/gluster-kubernetes#332]
Hi:

I cant add device to the cluster, pvcreate hang when it begin creating the volume, If I create the volume manually (inside pod, killing the existent pvcreate proccess) then the volume are created succesfully. So, how I can solve this to add devices from my topology files?

Inside Pod
```
[root@s-smartc2-zprei /]# pvcreate --metadatasize=128M --dataalignment=256K /dev/sdc
  Physical volume "/dev/sdc" successfully created.
```
From heketi-cli using my topology file
```
root@s-smartc2-zprei:/opt/kubernetes/glusterfs# heketi/heketi-cli topology load --json=topology.json
Creating cluster ... ID: 41b9620e754c79f56fc4cac8a8855e0c
        Creating node s-smartc2-zprei ... ID: 1f28a07d5be55e8839fa11b0551ef693
                Adding device /dev/sdc ... ^C
root@s-smartc2-zprei:/opt/kubernetes/glusterfs#
```
---------------

Proccess running inside pods when I try to add device from my topology using heketi-cli
```
root      3195     0  0 09:39 ?        00:00:00 pvcreate --metadatasize=128M --dataalignment=256K /dev/sdc
root      5228     0  0 11:02 ?        00:00:00 pvcreate --metadatasize=128M --dataalignment=256K /dev/sdc
```
----------------

My topology file
```
{
  "clusters": [
    {
      "nodes": [
        {
          "node": {
            "hostnames": {
              "manage": [
                "s-smartc2-zprei"
              ],
              "storage": [
                "192.168.133.2"
              ]
            },
            "zone": 1
          },
          "devices": [
            "/dev/sdc"
          ]
        },
        {
          "node": {
            "hostnames": {
              "manage": [
                "s-smartc3-zprei"
              ],
              "storage": [
                "192.168.133.3"
              ]
            },
            "zone": 1
          },
          "devices": [
            "/dev/sdc"
          ]
        },
        {
          "node": {
            "hostnames": {
              "manage": [
                "s-smartc4-zprei"
              ],
              "storage": [
                "192.168.133.4"
              ]
            },
            "zone": 1
          },
          "devices": [
            "/dev/sdc"
          ]
        }
      ]
    }
  ]
}
```
-----------------

Regards

**Comment by jarrpa** [comment]
@felixPG Edited your initial comment for better clarity. :)

It sounds like your storage devices were somehow misconfigured. Deleting the Kube resources probably didn't do anything, I'm guessing the `wipefs -a` is what did it. Can you reliably recreate the problem? If so, please try the following:
* Run your same `gk-deploy` command with `--load` at the end.
* If it still hangs, cancel and do a `wipefs -a` on the storage devices and then run with `--load` again.

This will tell us if there's something weird with the storage devices.

**Comment by felixPG** [comment]
@jarrpa I dont use gk-deploy, I make a deployment from json file, here the output from scratch again and working OK, if I have a time today I will recreate the problem with only wipefs:

------

root@s-smartc2-zprei:/opt/kubernetes/glusterfs# kubectl get pods
NAME                     READY     STATUS              RESTARTS   AGE
glusterfs-72rcn          1/1       Running             0          57s
glusterfs-hfvrd          1/1       Running             0          57s
glusterfs-msqlp          1/1       Running             0          57s
heketi-730120522-d36p6   0/1       ContainerCreating   0          3s
root@s-smartc2-zprei:/opt/kubernetes/glusterfs#
root@s-smartc2-zprei:/opt/kubernetes/glusterfs#
root@s-smartc2-zprei:/opt/kubernetes/glusterfs# kubectl get pods
NAME                     READY     STATUS    RESTARTS   AGE
glusterfs-72rcn          1/1       Running   0          59s
glusterfs-hfvrd          1/1       Running   0          59s
glusterfs-msqlp          1/1       Running   0          59s
heketi-730120522-d36p6   0/1       Running   0          5s
root@s-smartc2-zprei:/opt/kubernetes/glusterfs# curl s-smartc2-zprei:30625/hello
Hello from Heketiroot@s-smartc2-zprei:/opt/kubernetes/glusterfs#
root@s-smartc2-zprei:/opt/kubernetes/glusterfs#
root@s-smartc2-zprei:/opt/kubernetes/glusterfs# modprobe dm_thin_pool
root@s-smartc2-zprei:/opt/kubernetes/glusterfs# heketi/heketi-cli -s http://s-smartc2-zprei:30625 topology load --json=topology.json
Creating cluster ... ID: af1c20b802a3a6cb502e49d601fa537e
        Creating node s-smartc2-zprei ... ID: f495f64a829cabe40ad703d96e6c5db3
                Adding device /dev/sdc ... OK
        Creating node s-smartc3-zprei ... ID: ef0c6c2211bf0db835e49fb25e39c375
                Adding device /dev/sdc ... OK
        Creating node s-smartc4-zprei ... ID: 179ff5cbc16d939ba601655a739bc032
                Adding device /dev/sdc ... OK
root@s-smartc2-zprei:/opt/kubernetes/glusterfs#

-----
Thanks
