### ISSUE TITLE
GlusterFS in Pods that support geo-replication ? cross datacenter replication between two distinsctive zone 

### ISSUE THREAD

**Issue by mcousine** [gluster/gluster-kubernetes#333]
Hi i would like to know if GlusterFS in Pods support cross datacenter replication ? 

I.E Have a pool of 3 gluster FS on Zone datacenter1 wich have sychnonous data replication between them and have another Zone datacenter 2 which has also 3 glsuterfs Pods which also has synchronous replication . 

Now could we have asynchronous géo replication between Zone  []((http://gluster.readthedocs.io/en/latest/Administrator%20Guide/Geo%20Replication/))? or can we have Synchronous replication accross datacenter any latencies issues boundaries ?

**Comment by mcousine** [comment]
I received confirmation from Redhat that Geo-Replication is supported with Containerized Native Storage keep up good work community. 

https://access.redhat.com/documentation/en-us/red_hat_gluster_storage/3.2/html/administration_guide/chap-managing_geo-replication

**Comment by jarrpa** [comment]
@mcousine Great that you found that! :) Can the issue be closed, then?

**Comment by mcousine** [comment]
Yes

**Comment by renich** [comment]
There is, literally, zero information in the docs on how to georeplicate a pod or a PC for that matter. Care to elaborate?
