### ISSUE TITLE
Unable to mount volumes for pod "deploy-heketi ( CoreOS + Kubernetes 1.7.1 BareMetal)

### ISSUE THREAD

**Issue by amit2277** [gluster/gluster-kubernetes#340]
Hello Geeks,
I have installed Kubernetes 1.7.1 on CoreOS (Container Linux latest version) on four bare metal one controller and three worker nodes, Now i would like to configure GlusterFS inside these workers. I found this url to configure Glusterfs inside Kubernetes Cluster. I have tried the script but initially it failed. So I have started to install manually. I successfully apply(Created)  glusterfs-daemonset.yaml and can see pods are running fine and glusterfs service is up now when I deploy deploy-heketi-deployment.yaml it gives error. 
Setup:  Core OS on Bare Metal  + Kubernetes 1.7.1 
I have crated /dev/loop0 (25 GB) fake block storage because it has only one RAID SDA drive /dev/sda. 
Followed this link (https://techdev.de/glusterfs-in-bare-metal-kubernetes/)

Now when i deploy deploy-heketi-deployment.yaml it pod unable to mount.  Please help me out with this.

Error::::: 

Events:
  FirstSeen     LastSeen        Count   From                    SubObjectPath   Type            Reason          Message
  ---------     --------        -----   ----                    -------------   --------        ------          -------
  1h            46s             52      kubelet, 192.168.XX.XX                  Warning         FailedMount     Unable to mount volumes for pod "deploy-heketi-4004534255-7b5xt_default(9a070497-8fd3
-11e7-ad6f-9c8e992d4ab8)": timeout expired waiting for volumes to attach/mount for pod "default"/"deploy-heketi-4004534255-7b5xt". list of unattached/unmounted volumes=[config]
  1h            46s             52      kubelet, 192.168.51.85                  Warning         FailedSync      Error syncing pod
  1h            16s             66      kubelet, 192.168.51.85                  Warning         FailedMount     MountVolume.SetUp failed for volume "config" : secrets "heketi-config-secret" not found

So we manually create secret key using yaml. And still gives error- Pod (container) not able to load.

FirstSeen     LastSeen        Count   From                    SubObjectPath                   Type            Reason                  Message
  ---------     --------        -----   ----                    -------------                   --------        ------                  -------
  1m            1m              1       default-scheduler                                       Normal          Scheduled               Successfully assigned deploy-heketi-4004534255-j5510 to 192.1
68.51.84
  1m            1m              1       kubelet, 192.168.xx.xx                                 Normal          SuccessfulMountVolume   MountVolume.SetUp succeeded for volume "db" 
  1m            1m              1       kubelet, 192.168.xx.xx                               Normal          SuccessfulMountVolume   MountVolume.SetUp succeeded for volume "config" 
  1m            1m              1       kubelet, 192.168.xx.xx                                  Normal          SuccessfulMountVolume   MountVolume.SetUp succeeded for volume "heketi-service-accoun
t-token-lwhvl" 
  1m            20s             4       kubelet, 192.168.xx.xx  spec.containers{deploy-heketi}  Normal          Pulled                  Container image "heketi/heketi:dev" already present on machin
e
  1m            20s             4       kubelet, 192.168.xx.xx  spec.containers{deploy-heketi}  Normal          Created                 Created container
  1m            20s             4       kubelet, 192.168.xx.xx  spec.containers{deploy-heketi}  Normal          Started                 Started container
  1m            1s              9       kubelet, 192.168.xx.xx spec.containers{deploy-heketi}  Warning         BackOff                 Back-off restarting failed container
  1m            1s              9       kubelet, 192.168.xx.xx                                  Warning         FailedSync              Error syncing pod

On Worker node Docker logs shows that 
/etc/heketi/heketi.json file not found.

would appreciate help.

Thanks

**Comment by jarrpa** [comment]
The script does a fair amount of automagic things, so you'll be running
into a few of these headaches along the way. The easier thing to do would
be to try and run the script then show us the verbose ( -v ) logs and the
logs/events of the failing pods. Otherwise just inspect the script and
follow the commands it executes. In this instance, you're probably not
creating the config secret with the heketi.json file in the key it expects.

--Jose

**Comment by amit2277** [comment]
Thank for the reply Jarrpa,

When I run script ::

./gk-deploy -g -c kubectl -t ./kube-templates -l ./log.txt -v topology.json
[Y]es, [N]o? [Default: Y]: Y
./gk-deploy: line 576: python: command not found
Using Kubernetes CLI.
Checking status of namespace matching 'default':
default   Active    12d
Using namespace "default".
Checking for pre-existing resources...
  GlusterFS pods ... 
Checking status of pods matching '--selector=glusterfs=pod':
Timed out waiting for pods matching '--selector=glusterfs=pod'. not found.
  deploy-heketi pod ... 
Checking status of pods matching '--selector=deploy-heketi=pod':
Timed out waiting for pods matching '--selector=deploy-heketi=pod'. not found.
  heketi pod ... 
Checking status of pods matching '--selector=heketi=pod':
Timed out waiting for pods matching '--selector=heketi=pod'. not found.
  gluster-s3 pod ... 
Checking status of pods matching '--selector=glusterfs=s3-pod':
Timed out waiting for pods matching '--selector=glusterfs=s3-pod'. not found.
Creating initial resources ... kubectl -n default create -f ./kube-templates/heketi-service-account.yaml 2>&1
Error from server (AlreadyExists): error when creating "./kube-templates/heketi-service-account.yaml": serviceaccounts "heketi-service-account" already exists
kubectl -n default create clusterrolebinding heketi-sa-view --clusterrole=edit --serviceaccount=default:heketi-service-account 2>&1
Error from server (AlreadyExists): clusterrolebindings.rbac.authorization.k8s.io "heketi-sa-view" already exists
kubectl -n default label --overwrite clusterrolebinding heketi-sa-view glusterfs=heketi-sa-view heketi=sa-view
clusterrolebinding "heketi-sa-view" not labeled
OK
Marking '' as a GlusterFS node.
kubectl -n default label nodes  storagenode=glusterfs --overwrite 2>&1
error: resource(s) were provided, but no name, label selector, or --all flag specified
Failed to label node ''

When I try with sh -x gk-deploy -g -c kubectl -t ./kube-templates -l ./log.txt -v topology.json

# sh -x gk-deploy -g -c kubectl -t ./kube-templates -l ./log.txt -v topology.json
++ basename gk-deploy
+ PROG=gk-deploy
+++ dirname gk-deploy
++ cd .
++ pwd
+ SCRIPT_DIR=/root/deploy
+ TOPOLOGY=topology.json
+ LOG_FILE=
+ VERBOSE=0
+ CLI=
+ GLUSTER=0
+ KUBE_TEMPLATES_DEFAULT=/root/deploy/kube-templates
+ OCP_TEMPLATES_DEFAULT=/root/deploy/ocp-templates
+ TEMPLATES=
+ NAMESPACE=
+ WAIT=300
+ ABORT=0
+ NODES=
+ SKIP_PREREQ=0
+ EXISTS_GLUSTERFS=0
+ EXISTS_DEPLOY_HEKETI=0
+ EXISTS_HEKETI=0
+ EXISTS_OBJECT=0
+ EXECUTOR=kubernetes
+ SSH_KEYFILE=/dev/null
+ SSH_USER=root
+ SSH_SUDO=false
+ SSH_PORT=22
+ ADMIN_KEY=
+ USER_KEY=
+ DAEMONSET_LABEL=
+ DEPLOY_OBJECT=1
+ OBJ_ACCOUNT=
+ OBJ_USER=
+ OBJ_PASSWORD=
+ OBJ_STORAGE_CLASS=glusterfs-for-s3
+ OBJ_CAPACITY=2Gi
**gk-deploy: line 200: syntax error near unexpected token `<'**
**gk-deploy: line 200: `  done < <('**

can you please guide where is the issue.

**Comment by SaravanaStorageNetwork** [comment]
@amit2277  You need to have python installed.

Refer this to get basic requirements right:
https://github.com/gluster/gluster-kubernetes/blob/master/deploy/gk-deploy#L514

**Comment by amit2277** [comment]
Thanks  SaravanaStorageNetwork,

I have installed python and successfully run the script now we gets error.


Creating cluster ... ID: 40062bba922882ace1a6be5842aac712
Creating node 192.168.51.83 ... Unable to create node: New Node doesn't have glusterd running
Creating node 192.168.51.84 ... Unable to create node: New Node doesn't have glusterd running
Creating node 192.168.51.85 ... Unable to create node: New Node doesn't have glusterd running
Error loading the cluster topology.
Please check the failed node or device and rerun this script.

but i have checked each pod glusterd service are running fine on all pods.

also 
default           deploy-heketi-2199298601-m1kxw              1/1       Running 
default           glusterfs-815nj                             1/1       Running           
default           glusterfs-ptf3j                             1/1       Running             
default           glusterfs-v889m                             1/1       Running 

So seems everything works fine. do we have to do anything else regarding the error above?

Let me check creating volumes. update you the status.

**Comment by amit2277** [comment]
Resolve the issue :  
1)Installed python 
2) ./gk_deploy --abort 
3) deleted glusterfs pods 
4) deleted /etc/glusterfs and /var/lib/glusterd directories
rerun gk-deploy script - works like a charm 
Thank you very much for help

**Comment by jarrpa** [comment]
@amit2277 Good to hear! Sorry I didn't get to you earlier, I wasn't awake yet and today was a holiday. :)

If the problem is resolved, please feel free to close this Issue.

**Comment by amit2277** [comment]
Thanks Jarrpa :)  it just time difference :) 

Thanking from my team for this awesome development for Glusterfs+Kuberentes  :)
