### ISSUE TITLE
Heketi GlusterFS Volume Management

### ISSUE THREAD

**Issue by ronakpandya7** [gluster/gluster-kubernetes#342]
Hello,
Query : How heketi works (creates replica , strip, dispres volumes)  - Is it possible to create volume manually defining bricks using yaml? 

We have three gluserfs pods running on three worker nodes and we have deploy heketi rest api successfully
Now we want to distribute our data on all three worker nodes using 2 replicas.
So what we are missing here ?
Below is our YAML file for storage class.

********************************************
apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: gluster-heketi
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: "http://10.3.0.213:8080"
  volumetype: "replicate:2"
********************************************
By running this file it will automatically creates two bricks and two replicas..

 
Volume Name: vol_088179ad67a29ecb249a15442fbc50f8
Type: Replicate
Volume ID: 6b1c93e5-c241-4e57-9bb1-66c7bbfdc05e
Status: Started
Snapshot Count: 0
Number of Bricks: 1 x 2 = 2
Transport-type: tcp
Bricks:
Brick1: 192.168.51.XX:/var/lib/heketi/mounts/vg_5b152dda674797cd0a214ccec276b6d8/brick_59d1ffb3b552835ed9501d0e0c67c710/brick
Brick2: 192.168.51.XX:/var/lib/heketi/mounts/vg_32f498fd4bd3c18b8b7a549bf1821ebc/brick_a17ac334d0c1a4abe4fd428e819756dc/brick
Options Reconfigured:
transport.address-family: inet
nfs.disable: on

But we want to create volume distributed with two replica across three gluster pods. How can we achieve it? 
any help would be appreicated

**Comment by jarrpa** [comment]
heketi intentionally obfuscates some of the more granular features of GlusterFS. The only way to create GlusterFS volumes outside of the configurations heketi offers would be to have a non-heketi-managed cluster that you manually create volumes on, then manually create PVs bound to those volumes.

The only other method currently available for creating volumes through heketi is through `heketi-cli`. However, I think you can approximate what you want through the StorageClass using `volumetype: disperse`. Refer to the following documentation (for heketi-cli) of what the different options mean:

https://github.com/heketi/heketi/wiki/Create-a-volume

I believe what you're looking for is a `volumetype` of `disperse:1:2` where `disperse-data = 1` and `reduncancy = 2`. Note, however, that this configuration is [not officially supported](https://access.redhat.com/documentation/en-us/red_hat_gluster_storage/3.2/html/administration_guide/sect-creating_distributed_dispered_volumes_1) by downstream Red Hat, so we make no guarantees this will work. :)

**Comment by jarrpa** [comment]
After more than a week of inactivity, closing this issue.
