### ISSUE TITLE
Upgrade GlusterFs from 3.10 to 3.12

### ISSUE THREAD

**Issue by grebois** [gluster/gluster-kubernetes#349]
There are several problem with reserved ports fixed in 3.12;

https://bugzilla.redhat.com/show_bug.cgi?id=1454418
https://review.gluster.org/#/c/17359/

Regretfully CentOs release is still 3.10:

http://mirror.centos.org/centos/7/storage/x86_64/

So for the time being there is this workaround;

https://github.com/gluster/gluster-kubernetes/pull/347

But would be great to have official upstream containers.

Thanks!

**Comment by jarrpa** [comment]
You bet! This is something I'm looking forward to as well. :) There are several solutions to this problem, which we will hopefully be exploring in the near future.

**Comment by jarrpa** [comment]
GlusterFS containers now run 3.12. Closing this Issue.
