### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by nick** [gluster/gluster-kubernetes#35]
Thanks for this project - it's been very useful. I've been trying to use it on a 3 node Kubernetes cluster installed via kubeadm on CentOS 7. While experimenting, I found a few enhancements that would be useful:

* The script expects heketi-cli to be in the path. Perhaps throw an error if it's not detected?
* Executing `rm -rf /var/lib/heketi` on `--abort` on all the nodes would save me having to do it manually if I need to start from scratch
* After `--abort` I need to manually run `vgs` followed by `vgremove -y <volume group starting with vg_>` so that the volumes are ready for a fresh install. Not sure if this can happen automatically on `--abort`

I also found I needed to ensure lvm2-monitor was active on all nodes or strange errors would crop up. If it wasn't running I had to do the following:

    systemctl restart lvm2-lvmetad.service
    systemctl restart lvm2-lvmetad.socket

I could then check the status with `systemctl status lvm2-monitor`

Hope this is useful!

**Comment by jarrpa** [comment]
Thank you for your participation! :) To address your suggestions:

 * Good idea. I need to check the output of the heketi-cli commands for errors as well, so I'll do both those things at around the same time.
 * I'm not sure what you mean by this one. `/var/lib/heketi` shouldn't exist on the kube nodes, the GlusterFS volume heketi uses for its database should be mounted to `/var/lib/heketi` within the heketi container. At best I could delete the contents of the volume, but that would still leave the volume around, which would be a problem.
 * I don't think I want to be messing directly with extant VGs in the deployment script. I'd have to be very careful to make sure I'm not deleting anything I shouldn't be, and likely prompting confirmation, at which point it's not much different from telling the admin to delete the VGs themselves.
 * Throwing in `systemctl` calls makes the script less agnostic to linux distro, which is something I'm aiming for (even if I'm currently only developing in RH-flavored distros) :)

I personally use the vagrant setup for my development and testing. There's a wonderful little plugin called 'sandbox' (`vagrant plugin install sandbox`) that manages a simple snapshot-based workflow:

```
./up.sh -> vagrant sandbox on -> <do stuff, mess it up> -> vagrant sandbox rollback -> <restart docker service on all the nodes, or just restart the VMs> -> <do stuff again>
```

which makes things fairly easy to automate.

**Comment by nick** [comment]
It seems that /var/lib/heketi on each node may be a leftover from the bootstrap heketi installation perhaps? Regardless, if I run --abort then I'll still have to manually rm -rf /var/lib/heketi on each node before running the script again.

**Comment by jarrpa** [comment]
I went looking and I see them in my setups too, but I've never had to rm the directories during my development. I can look into whether or not this is a good idea, depending on when the directories get made. After what point in the script's execution are you running the `--abort`?

**Comment by MohamedAshiqrh** [comment]
@jarrpa @nick yeah /var/lib/heketi will be present in all the gluster pod running nodes. That's where we persist the mount points for the bricks created for each volume. yeah abort can clean it up, will not cause any problem. ONLY when [this](https://github.com/gluster/gluster-kubernetes/blob/master/deploy/gk-deploy#L110) hits we are safe to remove it.

**Comment by jarrpa** [comment]
@MohamedAshiqrh That makes sense! :)

**Comment by jarrpa** [comment]
As all the original suggestions have been addressed or discussed, closing this issue.
