### ISSUE TITLE
cattle not pets

### ISSUE THREAD

**Issue by jurgenweber** [gluster/gluster-kubernetes#355]
The configuration of the [topology](https://github.com/gluster/gluster-kubernetes/blob/master/deploy/topology.json.sample) file implies that my nodes that manage GlusterFS bricks will becomes pets because I need to specify an IP address, the IP addresses of the nodes in use.

Is there a way to dynamically manage this?  I do not want to manage IP address of nodes because I simply don't care.

What happens when I do a rolling cluster upgrade and all nodes are replaced one by one by kops, etc. Will all of the volumes be lost and GlusterFS unstable? How to I update the topology file and have no operational issues.

**Comment by jarrpa** [comment]
The GlusterFS nodes must maintain a consistent network identity. Once you create a volume with a given set of node names (e.g. IP address) you can only use those names to access the volume. Further, the storage device identities must also remain consistent. Nodes you identify as storage nodes this must be pets by definition.

**Comment by jurgenweber** [comment]
yeah, ok. Cool. Thanks.
