### ISSUE TITLE
gk-deploy failed during labeling stating already has a value (glusterfs)

### ISSUE THREAD

**Issue by SaravanaStorageNetwork** [gluster/gluster-kubernetes#356]
gk-deploy failed during labeling stating already has a value (glusterfs), and --overwrite is false.

Complete logs below.

I think it is better to have --overwrite option while running this command:

> /usr/bin/oc -n store-project1 label nodes node1 storagenode=glusterfs 2>&1

**Logs:**

\# cns-deploy -n store-project1 -g topology.json --log-file=/var/log/1-cns-deploy.log --verbose 
Welcome to the deployment tool for GlusterFS on Kubernetes and OpenShift.

Before getting started, this script has some requirements of the execution
environment and of the container platform that you should verify.

The client machine that will run this script must have:
 * Administrative access to an existing Kubernetes or OpenShift cluster
 * Access to a python interpreter 'python'

Each of the nodes that will host GlusterFS must also have appropriate firewall
rules for the required GlusterFS ports:
 * 111   - rpcbind (for glusterblock)
 * 2222  - sshd (if running GlusterFS in a pod)
 * 3260  - iSCSI targets (for glusterblock)
 * 24006 - glusterblockd
 * 24007 - GlusterFS Management
 * 24008 - GlusterFS RDMA
 * 49152 to 49251 - Each brick for every volume on the host requires its own
   port. For every new brick, one new port will be used starting at 49152. We
   recommend a default range of 49152-49251 on each host, though you can adjust
   this to fit your needs.

The following kernel modules must be loaded:
 * dm_snapshot
 * dm_mirror
 * dm_thin_pool
 * dm_multipath
 * target_core_user

For systems with SELinux, the following settings need to be considered:
 * virt_sandbox_use_fusefs should be enabled on each node to allow writing to
   remote GlusterFS volumes

In addition, for an OpenShift deployment you must:
 * Have 'cluster_admin' role on the administrative account doing the deployment
 * Add the 'default' and 'router' Service Accounts to the 'privileged' SCC
 * Have a router deployed that is configured to allow apps to access services
   running in the cluster

Do you wish to proceed with deployment?

[Y]es, [N]o? [Default: Y]: Y
Using OpenShift CLI.

Checking status of namespace matching 'store-project1':
store-project1   Active    1h
Using namespace "store-project1".
Checking for pre-existing resources...
  GlusterFS pods ... 
Checking status of pods matching '--selector=glusterfs=pod':
No resources found.
Timed out waiting for pods matching '--selector=glusterfs=pod'.
not found.
  deploy-heketi pod ... 
Checking status of pods matching '--selector=deploy-heketi=pod':
No resources found.
Timed out waiting for pods matching '--selector=deploy-heketi=pod'.
not found.
  heketi pod ... 
Checking status of pods matching '--selector=heketi=pod':
No resources found.
Timed out waiting for pods matching '--selector=heketi=pod'.
not found.
  glusterblock-provisioner pod ... 
Checking status of pods matching '--selector=glusterfs=block-provisioner-pod':
No resources found.
Timed out waiting for pods matching '--selector=glusterfs=block-provisioner-pod'.
not found.
  gluster-s3 pod ... 
Checking status of pods matching '--selector=glusterfs=s3-pod':
No resources found.
Timed out waiting for pods matching '--selector=glusterfs=s3-pod'.
not found.
Creating initial resources ... /usr/bin/oc -n store-project1 create -f /usr/share/heketi/templates/deploy-heketi-template.yaml 2>&1
template "deploy-heketi" created
/usr/bin/oc -n store-project1 create -f /usr/share/heketi/templates/heketi-service-account.yaml 2>&1
serviceaccount "heketi-service-account" created
/usr/bin/oc -n store-project1 create -f /usr/share/heketi/templates/heketi-template.yaml 2>&1
template "heketi" created
/usr/bin/oc -n store-project1 create -f /usr/share/heketi/templates/glusterfs-template.yaml 2>&1
template "glusterfs" created
/usr/bin/oc -n store-project1 policy add-role-to-user edit system:serviceaccount:store-project1:heketi-service-account 2>&1
role "edit" added: "system:serviceaccount:store-project1:heketi-service-account"
/usr/bin/oc -n store-project1 adm policy add-scc-to-user privileged -z heketi-service-account
OK
Marking 'node1' as a GlusterFS node.
/usr/bin/oc -n store-project1 label nodes node1 storagenode=glusterfs 2>&1
error: 'storagenode' already has a value (glusterfs), and --overwrite is false
Failed to label node 'node1'

**Comment by jarrpa** [comment]
Already there: https://github.com/gluster/gluster-kubernetes/pull/339

**Comment by SaravanaStorageNetwork** [comment]
> Already there: #339 
cool - closing this
