### ISSUE TITLE
deploy-heketi  fails with "Can't open /dev/sdb exclusively.  Mounted filesystem?"

### ISSUE THREAD

**Issue by mcedica** [gluster/gluster-kubernetes#359]
Im trying to deploy on k8s running on GCE and I always fail with:

_Found node gke-cluster-1-default-pool-73ffc114-4d15 on cluster a1bf3b01c904cc190de6ca334dac0d60
Adding device /dev/sdb ... Unable to add device: Unable to execute command on glusterfs-38rmj:   Can't open /dev/sdb exclusively.  Mounted filesystem?_

If I manually ssh into the container and execute the same command I get the same error:
_kubectl exec -it glusterfs-38rmj bash
[root@gke-cluster-1-default-pool-73ffc114-4d15 /]#  pvcreate -vvvvv --metadatasize=128M --dataalignment=256K /dev/sdb
...
#toollib.c:3194       Processing device /dev/sdb.
#toollib.c:4142         Checking pvcreate arg /dev/sdb which has existing PVID: <none>.
#device/dev-io.c:524         /dev/sdb: open failed: Device or resource busy
#toollib.c:4150   Can't open /dev/sdb exclusively.  Mounted filesystem_?

I have 3 cluster nodes, each one has external ssd disk mounted on /dev/sdb. My topology.json is configured to only this disk.
Output of: df -h
_/dev/sdb        369G   69M  350G   1% /mnt/disks/ssd0_

I also tried to wipe out these but I get an error.:
 _sudo wipefs  -a /dev/sdb
wipefs: error: /dev/sdb: probing initialization failed: Device or resource busy_

I have a dev background so any help with this issue is appreciated . thx!

**Comment by jarrpa** [comment]
At a glance, it looks like your devices are not actually empty. You can use tools like `lsblk` to see if there is anything form `sdb` mounted. Also verify that `vgs` and `pvs` show no LVM volume groups or physical volumes (respectively) using those devices.

**Comment by mcedica** [comment]
this is what I thought too. However I was unable to find out who is using it
_[root@gke-cluster-1-default-pool-424627dc-15kx /]# lsblk
lsblk: dm-0: failed to get device path
lsblk: dm-0: failed to get device path
NAME    MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sda       8:0    0  100G  0 disk 
|-sda1    8:1    0 95.9G  0 part /var/lib/misc/glusterfsd
|-sda2    8:2    0   16M  0 part 
|-sda3    8:3    0    2G  0 part 
|-sda4    8:4    0   16M  0 part 
|-sda5    8:5    0    2G  0 part 
|-sda6    8:6    0  512B  0 part 
|-sda7    8:7    0  512B  0 part 
|-sda8    8:8    0   16M  0 part 
|-sda9    8:9    0  512B  0 part 
|-sda10   8:10   0  512B  0 part 
|-sda11   8:11   0    8M  0 part 
`-sda12   8:12   0   16M  0 part 
sdb       8:16   0  375G  0 disk 
[root@gke-cluster-1-default-pool-424627dc-15kx /]# vgs
[root@gke-cluster-1-default-pool-424627dc-15kx /]# pvs_

This is a brand new cluster, I only run ./gk-deploy -gvy multiple times on it ( as it failed at different stages)

**Comment by jarrpa** [comment]
Edited your comment for clarity. :) Please try to use `` ``` `` to surround terminal output.

Hmm... I saw you posted this earlier:
```
/dev/sdb 369G 69M 350G 1% /mnt/disks/ssd0
```
That would indicated that /dev/sdb is mounted somewhere, right? Can you try something like `umount /mnt/disks/ssd0` and then try `wipefs`?

**Comment by mcedica** [comment]
thx! sry for the formatting .
I managed to moved fwd and now it seems that the topology load attempts to execute on the same pod:
```
/usr/local/bin/kubectl -n default exec -i deploy-heketi-3019752013-xn69z -- heketi-cli -s http://localhost:8080 --user admin --secret '' topology load --json=/etc/heketi/topology.json 2>&1
Found node gke-cluster-1-default-pool-424627dc-15kx on cluster 4340d69b402e3ee0eaddf4e650162926
Found device /dev/sdb
Creating node gke-cluster-1-default-pool-424627dc-84d7 ... Unable to create node: Unable to execute command on glusterfs-g22sj:
Creating node gke-cluster-1-default-pool-424627dc-rq8h ... Unable to create node: Unable to execute command on glusterfs-g22sj:
Error loading the cluster topology.
Please check the failed node or device and rerun this script.
```
On the node that has succeed I see these in the logs:
```
[2017-09-19 21:59:29.901999] I [MSGID: 106004] [glusterd-handler.c:5882:__glusterd_peer_rpc_notify] 0-management: Peer <35.184.141.163> (<00000000-0000-0000-0000-000000000000>), in state <Establishing Connection>, has disconnected from glusterd.
[2017-09-19 21:59:29.902119] I [socket.c:3581:socket_submit_reply] 0-socket.management: not connected (priv->connected = -1)
[2017-09-19 21:59:29.902125] E [rpcsvc.c:1348:rpcsvc_submit_generic] 0-rpc-service: failed to submit message (XID: 0x1, Program: GlusterD svc cli, ProgVers: 2, Proc: 1) to rpc-transport (socket.management
```
However my initial issue is fixed so I am closing this. thx

**Comment by mcedica** [comment]
Just to clarify what the issue was in case anyone else runs into this: the disk was suppose to be attached but not mounted and formatted and this happens by default  when creating a brand new k8s cluster on GCE with local disk attached to nodes.
