### ISSUE TITLE
Use DaemonSet for GlusterFS

### ISSUE THREAD

**Issue by jarrpa** [gluster/gluster-kubernetes#36]
When https://github.com/heketi/heketi/pull/596 resolves and we get a new container image, update the GlusterFS definition to use DaemonSets instead of Deployments. For the OpenShift support, this means the use of Templates will also no longer be necessary.

**Comment by lpabon** [comment]
@jarrpa DaemonSet has been merged.

**Comment by obnoxxx** [comment]
closed by #38
