### ISSUE TITLE
Error: No space with recent gk-deploy

### ISSUE THREAD

**Issue by dougbtv** [gluster/gluster-kubernetes#363]
I've been running into an issue where, after the topology is loaded with `gk-deploy`, I have a failure that reads: `Error: No space`. I've been deploying this way with gk-deploy here and there for a few weeks using the same methodology, but, just started to run into issues this morning.

I've been deploying with this command:

```
./gk-deploy -n gluster -w 900 -g -y
```

And currently have a clone of gluster-kubernetes @ master HEAD.

```
[centos@kube-master deploy]$ git log --format="%H" -n 1
bd2a1d8b0b9f33f12347211d893e9f340f016d7d
```

I noticed that the `heketi/heketi:dev` image had been updated 26 hours previously, so I tried to to change the YAML resource specs to reference both `heketi/heketi:latest` and `heketi/heketi:4` both with the same results.

I also tried a deploy against a setup with kube 1.7.4. Same results, too.

Additionally I noticed [this issue](https://github.com/heketi/heketi/issues/466#issuecomment-244341110) which referneces the same: `Error: No space`. I've been using 10 gig disks (in a lab for testing as part of a wider setup), and that looked eerily similar so I tried bumping them up to 20 gigs, no luck.

Here's the full output from `gk-deploy`:

```
Using namespace "gluster".
Checking for pre-existing resources...
  GlusterFS pods ... not found.
  deploy-heketi pod ... not found.
  heketi pod ... not found.
  gluster-s3 pod ... not found.
  Creating initial resources ... serviceaccount "heketi-service-account" created
clusterrolebinding "heketi-sa-view" created
clusterrolebinding "heketi-sa-view" labeled
OK
node "kube-node-1" labeled
node "kube-node-2" labeled
daemonset "glusterfs" created
Waiting for GlusterFS pods to start ... OK
secret "heketi-config-secret" created
secret "heketi-config-secret" labeled
service "deploy-heketi" created
deployment "deploy-heketi" created
Waiting for deploy-heketi pod to start ... OK
Creating cluster ... ID: 65697713ded659f1b1aa9b5fd465a4a7
Allowing file volumes on cluster.
Allowing block volumes on cluster.
Creating node kube-node-1 ... ID: b4ea8e21a530b2a8f11baf82cfa58cc5
Adding device /dev/vdb ... OK
Creating node kube-node-2 ... ID: feec4365447ad44fb5f930fb17093138
Adding device /dev/vdb ... OK
heketi topology loaded.
Error: No space
Failed on setup openshift heketi storage
This may indicate that the storage must be wiped and the GlusterFS nodes must be reset.
```

My `topology.json` is as follows:

```
{
  "clusters": [
    {
      "nodes": [
                {
          "node": {
            "hostnames": {
              "manage": [
                "kube-node-1"
              ],
              "storage": [
                "192.168.1.154"
              ]
            },
            "zone": 1
          },
          "devices": [
            "/dev/vdb"
          ]
        },                {
          "node": {
            "hostnames": {
              "manage": [
                "kube-node-2"
              ],
              "storage": [
                "192.168.1.78"
              ]
            },
            "zone": 1
          },
          "devices": [
            "/dev/vdb"
          ]
        }              ]
    }
  ]
}
```

Currently using Kube 1.7.6

```
[centos@kube-master deploy]$ kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-08-31T09:14:02Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6", GitCommit:"4bc5e7f9a6c25dc4c03d4d656f2cefd21540e28c", GitTreeState:"clean", BuildDate:"2017-09-14T06:36:08Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by jarrpa** [comment]
@dougbtv You need a minimum of three nodes to create a replica 3 volume, which is the default in our configuration.

**Comment by dougbtv** [comment]
Welp, that was a glaring mistake on my part... Jarrpa, thanks for the eyes,
so much.

**Comment by dougbtv** [comment]
FWIW, after spinning it up again with the three nodes, I did have luck. However, I did after all have to change the heketi container image to the `heketi/heketi:4` tag down from `heketi/heketi:dev` tag. After doing that, looks like it's working a charm.

Even with 3 nodes, with `heketi/heketi:dev` I was still getting the `Error: No space` error during heketi-deploy.

**Comment by humblec** [comment]
@jarrpa any thoughts on above comment?

**Comment by jarrpa** [comment]
@humblec Hmm... nothing immediately comes to mind. I can't seem to replicate it.

@dougbtv If you're willing to help us out further, could you open a new Issue for this, including any information gathered thus far. Also, could you try `heketi/heketi:5` and see if that works for you as well? `heketi:latest` should match that, but it is not as new as `heketi:dev`. If you do try that, share that in the new issue as well.

**Comment by dougbtv** [comment]
More than happy to write an issue up and try with that tag. I'm headed off
on vacation, but... Keep your eyes peeled for next week, I'll document it
up and see if I can get enough info to make it reproducible.

**Comment by dougbtv** [comment]
Just an FYI @jarrpa I ran through a gk-deploy again, and this time with the `heketi/heketi:5` tagged image -- I don't get the "no space" error (e.g. everything completed as expected). I'll try `heketi:dev` again and file a new issue if I'm able to reproduce it again.

**Comment by jarrpa** [comment]
@dougbtv Neat! That's heartening. :)
