### ISSUE TITLE
heketi volume storage management

### ISSUE THREAD

**Issue by Justluckyg** [gluster/gluster-kubernetes#378]
This is more of a question/inquiry than an issue..

How and where can I edit the default number of replicas that heketi creates for the volumes? Currently it creates 3 bricks per PVC that I claim and I have a very limited storage space. I dont mind having no redundancy, I would like to know how I can configure it that it will only create a single brick/replica for every pvc I create so it wouldnt take too much space..

**Comment by jarrpa** [comment]
This is a per-volume option, the default is always 3-way replica. You can create a StorageClass that will set the volume type for you, where you could volumetype "none": https://github.com/kubernetes/examples/blob/master/staging/persistent-volume-provisioning/README.md#glusterfs

This corresponds to the heketi-cli volume create option of `--durability=none`.

**Comment by Justluckyg** [comment]
Thank you as always @jarrpa :) Just a question, whats the difference between `type: distribute` to `type: replicate`

When I did gluster volume info, im now seeing a single brick per volume after using volumetype: "none" to my storageClass.yaml file.

**Comment by SaravanaStorageNetwork** [comment]
> Thank you as always @jarrpa :) Just a question, whats the difference between type: distribute to type: replicate

Refer below to understand different volume types in glusterfs :
http://docs.gluster.org/en/latest/Quick-Start-Guide/Architecture/#types-of-volumes
In short, replicate provides redundancy whereas distribute does not. 

In Kubernetes environment, redundancy is important requirement hence replicate volume type is made as default.

You can write few files and see how the files are stored in the backend to get a better understanding.

**Comment by jarrpa** [comment]
@Justluckyg Did we manage to address your question adequately? If so, please close the issue. I'll close this in a few days if I hear nothing else. :)

**Comment by Justluckyg** [comment]
@jarrpa yup thank you let me close this now!
