### ISSUE TITLE
Gluster performance tuning

### ISSUE THREAD

**Issue by shadycuz** [gluster/gluster-kubernetes#386]
My first cluster of 3 nodes with 50gb SSD's landed me 30MB's in the cluster. I thought I would expand the cluster to 6 nodes and get double the performance. 
```
/ # dd if=/dev/zero of=/tmp/test1.img bs=1G count=1
1+0 records in
1+0 records out
1073741824 bytes (1.0GB) copied, 4.994342 seconds, 205.0MB/s
/ # dd if=/dev/zero of=/test/test1.img bs=1G count=1
1+0 records in
1+0 records out
1073741824 bytes (1.0GB) copied, 26.378093 seconds, 38.8MB/s
```

I picked up about 8 or 9 MB's per second. My SSD's are capable of 250MB's. Is my performance bad? Can I increase it somehow?I don't think its the network, but I can run some tests from node to node and pod to node.

Thanks,
Levi

**Comment by shadycuz** [comment]
Read is a bit more acceptable but not great.
```
/ # dd if=/dev/zero of=/test/test.img bs=1M count=1024
1024+0 records in
1024+0 records out
1073741824 bytes (1.0GB) copied, 24.519925 seconds, 41.8MB/s
/ # dd if=/test/test.img of=/dev/null bs=1M count=1024
1024+0 records in
1024+0 records out
1073741824 bytes (1.0GB) copied, 15.752262 seconds, 65.0MB/s
```

**Comment by JohnStrunk** [comment]
I'd definitely take a look at the network... If you're on a 1Gb network and using a replica 3 volume, you're pretty much at the limit: 1Gb/s ~ 120 MB/s ==> 120/(3 replicas) = 40 MB/s throughput.
If you're using 10G, then I'd expect better.

**Comment by shadycuz** [comment]
@JohnStrunk It's my network, only 1Gb. Remember when 1Gb was all you thought you would ever need.... Closing this.
