### ISSUE TITLE
Deleting volumes via heketi-cli works exactly once

### ISSUE THREAD

**Issue by gilgameshskytrooper** [gluster/gluster-kubernetes#387]
My set up: 3 Ubuntu 16.04 LTS node bare-metal cluster (2 workers getting IP's from a DHCP server running on master). Kubernetes 1.8.2, trying to run a [modified version](https://github.com/gilgameshskytrooper/stogit-gitlab-omnibus) of [gitlab-omnibus](https://gitlab.com/charts/charts.gitlab.io/tree/master/charts/gitlab-omnibus) to use GlusterFS as the storage provider rather than the default or GKE. Each node uses losetup to create a loopback device at /dev/loop200 at boot (which is directly fed to hyperconverged-Gluster installation via the ```./gk-deploy``` command via a topology file.

Doing the following after initializing a fresh instance of the hyperconverged gluster-kubernetes:  Doing ```helm install gitlab-omnibus --name glob``` ***(must use <=4 character name e.g. ```glob```,  for helm since using the default naming scheme and ```gitlab-omnibus``` will both overfill the 63 char limit for pod names)*** will install fine (albeit some errors on the gitlab chart side due to faulty configuration that I am still fine tuning. Next, running ```helm del --purge glob``` to delete the previous instance, everything gets removed without a problem. I do the following from the Kubernetes master to ensure that the volumes are really gone:
```
$kubectl exec -it (kubectl get pods | grep heketi | awk '{print $1}') -- /bin/bash
[root@heketi-....... /]# heketi-cli volume list
```
> all entries except heketidbstorage have been deleted (which is the expected behavior)

Then I do another install of the gitlab-omnibus via ```helm install gitlab-omnibus --name glob```. Although everything installs fine, the second installation did not correctly delete via ```helm del --purge glob```. Although helm did not give me any error messages, going back to:
```
$kubectl exec -it (kubectl get pods | grep heketi | awk '{print $1}') -- /bin/bash
[root@heketi-....... /]# heketi-cli volume list
```
showed 3 new volumes (each per node) which should have been deleted when helm deleted the instance of gitlab-omnibus.

Furthermore, I tried the following from the heketi pod:
```
[root@heketi-....... /]# heketi-cli volume delete $(heketi-cli volume list | grep Name:vg | awk '{print $1} | cut -c 4-)
```
***```grep Name:vg``` to ensure I don't delete heketidbstorage, ```cut -c 4-``` to cut out the chars ```Id:``` out of the first colume of text***
Which resulted in the command hanging up (no errors, or exit after a specified period of time)

To investigate further into why this was happening,  and ran the following on the nodes themselves ```lsof | grep /dev/loop200```. 2 of the nodes did not return anything. However, on the third node, I got the following response: 
```
lsof: no pwd entry for uid 81
lsof: no pwd entry for uid 81
lsof: no pwd entry for uid 81
lsof: no pwd entry for uid 81
.....
```
Next, I removed the hyperconverged instance of gluster-kubernetes via ```./gk-deploy -gy --abort```. However,  the one glusterfs pod running on the offending node failed to terminate (which causes the ```./gk-deploy``` script to fail with a timeout). Hence, I use force delete to remove the offending pod with the following ```kubectl delete pod glusterfs-.... --force --grace-period=0``` and then remove the glusterfs daemonset via ```kubectl delete daemonset (kubectl get daemonset | grep glusterfs | awk 'NR==1{print }')```.

After doing all this, I revisited the ```lsof | grep /dev/loop200``` command on the offending node, and this time around, the command showed that ```/dev/loop200``` was currently opened by ```vgremove```. However, trying to kill the ```vgremove``` using ```kill``` yielded no results.

Furthermore, trying to delete the faulty volume group directly via ```vgremove -ff $(vgdisplay | grep -i "VG Name" | awk '{print $3}')``` also failed with the message ```Logical volume contains a filesystem in use.```

However, force rebooting the cluster via ```sudo reboot -f``` removes the hung up ```vgremove``` process. Then I can reset the previous instance of the gluster-kubernetes via ```vgremove -ff $(vgdisplay | grep -i "VG Name" | awk '{print $3}') && rm -rf /var/lib/heketi /etc/glusterfs /var/lib/glusterd /var/log/glusterfs && wipefs -a -f /dev/loop200``` on each of the nodes, then running ```./gk-deploy -gy topology.json``` will successfully create a new instance of gluster-kubernetes.

Running this process multiple times, The following consistencies were observed:
1. It seems that each one of the 3 nodes have the capacity to become "an offending node" (i.e. vgremove hangs up), and I have to forcibly remove kubernetes-gluster, and reboot the cluster.
2. Exactly 1 node becomes the offending node (running ```lsof | grep /dev/loop200``` will not return anything on 2 nodes, but will return ```lsof: no pwd entry ...``` on exactly 1 node
3. The first installation and removal of gitlab-omnibus always succeeds, the second installation succeeds but fails to delete correctly (due to the offending node bug outlined above).

Although I highly doubt it, this ***COULD*** be related to how the gitlab-omnibus was writen in. But a careful look at all the storage configurations, and nothing seems to be amiss.

Please let me know what other tests I could do, or if I am doing something wrong. Thank you!

**Comment by jarrpa** [comment]
Unfortunately, I have no experience with Helm charts, so I don't know what it's doing when it's deleting gitlab-omnibus. 

The only thing that really stands out for me is the use of loopback devices. I understand that they are presented as functionally identical to actual block devices but we do not recommend going this route. There's a chance the problem is there.

heketi uses LVM commands to directly manipulate the storage devices it manages. It manages devices as PVs, creats VGs on them, and creates and destroys LVs for GlusterFS bricks as needed. I'm not sure if all this LVM activity would somehow be different or a stress on a loopback device.

**Comment by gilgameshskytrooper** [comment]
Any suggestions on how to set up an actual block device? I don't think I utilized LVM when I first installed Ubuntu on the nodes, so if the only way is to explicitly set a separate data partition, I would have to start over.

If there is an alternate approach I can take, please advise.

**Comment by jarrpa** [comment]
You're not supposed to use LVM or do any setup on the block devices. They need to be bare block devices, with no partitions and no use by LVM. Since you're using bare-metal nodes, you would need to just add something like an HDD, an SSD, a JBOD, etc. that is intended only for use by GlusterFS/heketi.

I will mention that I am not a complete expert when it comes to block storage, so I don't know if there are any nuances or caveats when using loopback files as block devices. All I can say for certain is that we (the repo maintainers) have not experimented/tested with loopback mounts for this project. I also believe there have been others raising Issues here that were trying to use loopback devices that we advised against doing that.

**Comment by gilgameshskytrooper** [comment]
ahh! Good to know. I will get back to u when i set this up
