### ISSUE TITLE
Error from server (NotFound): services "heketi" not found

### ISSUE THREAD

**Issue by olegsmetanin** [gluster/gluster-kubernetes#390]
I have deployed Kubernetes cluster (1 master+2 nodes) using Kubespray on ScaleWay (Ubuntu Xenial, 16.04 latest)). When install gluster-kubernetes (origin/master, 2017-11-13) the gk-deploy script says "Error from server (NotFound): services "heketi" not found".

```
$ ./gk-deploy -gvy
Using Kubernetes CLI.

Checking status of namespace matching 'default':
default   Active    31m
Using namespace "default".
Checking for pre-existing resources...
  GlusterFS pods ...
Checking status of pods matching '--selector=glusterfs=pod':

found.
  deploy-heketi pod ...
Checking status of pods matching '--selector=deploy-heketi=pod':

found.
  heketi pod ...
Checking status of pods matching '--selector=heketi=pod':

found.
  gluster-s3 pod ...
Checking status of pods matching '--selector=glusterfs=s3-pod':

found.
Determining heketi service URL ... Error from server (NotFound): services "heketi" not found
Error from server (NotFound): services "heketi" not found
Error from server (NotFound): services "heketi" not found
Error from server (NotFound): services "heketi" not found
```

**Comment by jarrpa** [comment]
What are you trying to do? You've clearly already deployed GlusterFS and heketi, so why are you running it again?

**Comment by olegsmetanin** [comment]
Actually, it is first run of ./gk-deploy -gvy on ordinal Kubernetes installation without GlusterFS.
```
kubectl get all --all-namespaces
NAMESPACE     NAME              DESIRED   CURRENT   READY     UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
kube-system   ds/kube-flannel   3         3         3         3            3           <none>          6h

NAMESPACE     NAME                          DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
kube-system   deploy/kube-dns               2         2         2            2           5h
kube-system   deploy/kubedns-autoscaler     1         1         1            1           5h
kube-system   deploy/kubernetes-dashboard   1         1         1            1           5h

NAMESPACE     NAME                                 DESIRED   CURRENT   READY     AGE
kube-system   rs/kube-dns-cf9d8c47                 2         2         2         5h
kube-system   rs/kubedns-autoscaler-86c47697df     1         1         1         5h
kube-system   rs/kubernetes-dashboard-7fd45476f8   1         1         1         5h

NAMESPACE     NAME                          DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
kube-system   deploy/kube-dns               2         2         2            2           5h
kube-system   deploy/kubedns-autoscaler     1         1         1            1           5h
kube-system   deploy/kubernetes-dashboard   1         1         1            1           5h

NAMESPACE     NAME              DESIRED   CURRENT   READY     UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
kube-system   ds/kube-flannel   3         3         3         3            3           <none>          6h

NAMESPACE     NAME                                 DESIRED   CURRENT   READY     AGE
kube-system   rs/kube-dns-cf9d8c47                 2         2         2         5h
kube-system   rs/kubedns-autoscaler-86c47697df     1         1         1         5h
kube-system   rs/kubernetes-dashboard-7fd45476f8   1         1         1         5h

NAMESPACE     NAME                                       READY     STATUS    RESTARTS   AGE
kube-system   po/kube-apiserver-master01                 1/1       Running   0          5h
kube-system   po/kube-controller-manager-master01        1/1       Running   0          5h
kube-system   po/kube-dns-cf9d8c47-bl788                 3/3       Running   0          5h
kube-system   po/kube-dns-cf9d8c47-lbdk7                 3/3       Running   0          5h
kube-system   po/kube-flannel-mnqf2                      2/2       Running   0          6h
kube-system   po/kube-flannel-qxgds                      2/2       Running   0          6h
kube-system   po/kube-flannel-rtz6l                      2/2       Running   0          6h
kube-system   po/kube-proxy-master01                     1/1       Running   0          6h
kube-system   po/kube-proxy-node01                       1/1       Running   0          6h
kube-system   po/kube-proxy-node02                       1/1       Running   0          6h
kube-system   po/kube-scheduler-master01                 1/1       Running   0          5h
kube-system   po/kubedns-autoscaler-86c47697df-vqnll     1/1       Running   0          5h
kube-system   po/kubernetes-dashboard-7fd45476f8-j8l4h   1/1       Running   0          5h
kube-system   po/nginx-proxy-node01                      1/1       Running   0          6h
kube-system   po/nginx-proxy-node02                      1/1       Running   0          6h

NAMESPACE     NAME                       TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)         AGE
default       svc/kubernetes             ClusterIP   10.233.0.1      <none>        443/TCP         6h
kube-system   svc/kube-dns               ClusterIP   10.233.0.3      <none>        53/UDP,53/TCP   5h
kube-system   svc/kubernetes-dashboard   ClusterIP   10.233.58.138   <none>        80/TCP          5h
```

**Comment by olegsmetanin** [comment]
```
 ./gk-deploy -gvy --abort
Using Kubernetes CLI.

Checking status of namespace matching 'default':
default   Active    6h
Using namespace "default".
Removing heketi resources.
/usr/local/bin/kubectl -n default delete all,svc,jobs,deploy,secret --selector="deploy-heketi" 2>&1
No resources found
/usr/local/bin/kubectl -n default delete all,svc,deploy,secret,sa,clusterrolebinding --selector="heketi" 2>&1
No resources found
Removing gluster-s3 resources.
/usr/local/bin/kubectl -n default delete all,svc,deploy,secret,sc --selector="gluster-s3" 2>&1
No resources found
Removing label from 'master01' as a GlusterFS node.
/usr/local/bin/kubectl -n default label nodes "master01" storagenode- 2>&1
label "storagenode" not found.
node "master01" not labeled
Removing label from 'node01' as a GlusterFS node.
/usr/local/bin/kubectl -n default label nodes "node01" storagenode- 2>&1
label "storagenode" not found.
node "node01" not labeled
Removing label from 'node02' as a GlusterFS node.
/usr/local/bin/kubectl -n default label nodes "node02" storagenode- 2>&1
label "storagenode" not found.
node "node02" not labeled
Removing glusterfs daemonset.
/usr/local/bin/kubectl -n default delete ds --selector="glusterfs" 2>&1
No resources found


./gk-deploy -gvy
Using Kubernetes CLI.

Checking status of namespace matching 'default':
default   Active    6h
Using namespace "default".
Checking for pre-existing resources...
  GlusterFS pods ...
Checking status of pods matching '--selector=glusterfs=pod':

found.
  deploy-heketi pod ...
Checking status of pods matching '--selector=deploy-heketi=pod':

found.
  heketi pod ...
Checking status of pods matching '--selector=heketi=pod':

found.
  gluster-s3 pod ...
Checking status of pods matching '--selector=glusterfs=s3-pod':

found.
Determining heketi service URL ... Error from server (NotFound): services "heketi" not found
Error from server (NotFound): services "heketi" not found
Error from server (NotFound): services "heketi" not found
```

**Comment by jarrpa** [comment]
....that doesn't make any sense. What's the output of `kubectl get pod --show-all --selector=glusterfs=pod`?

**Comment by tlymki** [comment]
I have the same issue with Error from server (NotFound): services "heketi" not found,

 
kubectl get pod --show-all --selector=glusterfs=pod
No resources found.

**Comment by tlymki** [comment]
./gk-deploy -g
Welcome to the deployment tool for GlusterFS on Kubernetes and OpenShift.

Before getting started, this script has some requirements of the execution
environment and of the container platform that you should verify.

The client machine that will run this script must have:
 * Administrative access to an existing Kubernetes or OpenShift cluster
 * Access to a python interpreter 'python'

Each of the nodes that will host GlusterFS must also have appropriate firewall
rules for the required GlusterFS ports:
 * 2222  - sshd (if running GlusterFS in a pod)
 * 24007 - GlusterFS Management
 * 24008 - GlusterFS RDMA
 * 49152 to 49251 - Each brick for every volume on the host requires its own
   port. For every new brick, one new port will be used starting at 49152. We
   recommend a default range of 49152-49251 on each host, though you can adjust
   this to fit your needs.

The following kernel modules must be loaded:
 * dm_snapshot
 * dm_mirror
 * dm_thin_pool

For systems with SELinux, the following settings need to be considered:
 * virt_sandbox_use_fusefs should be enabled on each node to allow writing to
   remote GlusterFS volumes

In addition, for an OpenShift deployment you must:
 * Have 'cluster_admin' role on the administrative account doing the deployment
 * Add the 'default' and 'router' Service Accounts to the 'privileged' SCC
 * Have a router deployed that is configured to allow apps to access services
   running in the cluster

Do you wish to proceed with deployment?

[Y]es, [N]o? [Default: Y]: y
Using Kubernetes CLI.
Using namespace "default".
Checking for pre-existing resources...
  GlusterFS pods ... found.
  deploy-heketi pod ... found.
  heketi pod ... found.
  gluster-s3 pod ... found.
Error from server (NotFound): services "heketi" not found
Error from server (NotFound): services "heketi" not found
Error from server (NotFound): services "heketi" not found
Error from server (NotFound): services "heketi" not found
^C

**Comment by tlymki** [comment]
kubectl get all --all-namespaces
NAMESPACE     NAME                                       READY     STATUS    RESTARTS   AGE
default       po/busybox-3810894669-nl700                1/1       Running   4          3h
kube-system   po/elasticsearch-logging-v1-rgxj9          1/1       Running   0          4h
kube-system   po/elasticsearch-logging-v1-skvn1          1/1       Running   0          4h
kube-system   po/fluentd-es-v1.20-55k1r                  1/1       Running   0          4h
kube-system   po/fluentd-es-v1.20-t9gfs                  1/1       Running   0          4h
kube-system   po/fluentd-es-v1.20-wp9j6                  1/1       Running   0          4h
kube-system   po/heapster-v1.2.0-3368556192-8xmwr        4/4       Running   0          4h
kube-system   po/kibana-logging-2931259027-1qj79         1/1       Running   0          4h
kube-system   po/kube-dns-v20-ntbr0                      3/3       Running   0          2h
kube-system   po/kubernetes-dashboard-4118084468-0h3t9   1/1       Running   0          4h
kube-system   po/monitoring-influxdb-grafana-v4-ztvg9    2/2       Running   0          2h

NAMESPACE     NAME                                DESIRED   CURRENT   READY     AGE
kube-system   rc/elasticsearch-logging-v1         2         2         2         4h
kube-system   rc/kube-dns-v20                     1         1         1         4h
kube-system   rc/monitoring-influxdb-grafana-v4   1         1         1         4h

NAMESPACE     NAME                        CLUSTER-IP      EXTERNAL-IP   PORT(S)             AGE
default       svc/kubernetes              10.77.0.1       <none>        443/TCP             5h
kube-system   svc/elasticsearch-logging   10.77.15.94     <none>        9200/TCP            4h
kube-system   svc/heapster                10.77.105.221   <none>        80/TCP              4h
kube-system   svc/kibana-logging          10.77.167.2     <none>        5601/TCP            4h
kube-system   svc/kube-dns                10.77.0.10      <none>        53/UDP,53/TCP       4h
kube-system   svc/kubernetes-dashboard    10.77.150.91    <nodes>       80:31406/TCP        4h
kube-system   svc/monitoring-grafana      10.77.151.206   <none>        80/TCP              4h
kube-system   svc/monitoring-influxdb     10.77.135.125   <none>        8083/TCP,8086/TCP   2h

NAMESPACE     NAME                          DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
default       deploy/busybox                1         1         1            1           3h
kube-system   deploy/heapster-v1.2.0        1         1         1            1           4h
kube-system   deploy/kibana-logging         1         1         1            1           4h
kube-system   deploy/kubernetes-dashboard   1         1         1            1           4h

NAMESPACE     NAME                                 DESIRED   CURRENT   READY     AGE
default       rs/busybox-3810894669                1         1         1         3h
kube-system   rs/heapster-v1.2.0-3368556192        1         1         1         4h
kube-system   rs/heapster-v1.2.0-3418333736        0         0         0         4h
kube-system   rs/kibana-logging-2931259027         1         1         1         4h
kube-system   rs/kubernetes-dashboard-4118084468   1         1         1         4h

there are no any pods or entities of glusterFS or heketi-deployment

**Comment by jarrpa** [comment]
@tlymki Please paste all output of the command I requested, including any whitespace, and enclose it in `` ``` `` marks.

**Comment by tlymki** [comment]
[centos@k8s-master ~]$ ```kubectl get pod --show-all --selector=glusterfs=pod
No resources found.```

**Comment by jarrpa** [comment]
@olegsmetanin @tlymki Should be fixed with https://github.com/gluster/gluster-kubernetes/pull/391. Please confirm.

**Comment by olegsmetanin** [comment]
I confirm, this error has gone.

**Comment by tlymki** [comment]
Yes, everything works good enough, thnx
