### ISSUE TITLE
why do you recommend glusterfs set 3 replicas not 2?

### ISSUE THREAD

**Issue by yu-yang2** [gluster/gluster-kubernetes#396]
I notice the readme `https://github.com/gluster/gluster-kubernetes/blob/master/docs/examples/dynamic_provisioning_external_gluster/README.md` recommend to use 3 replicas in a 3 nodes cluster, why not use 2? Dosen't it save more space?

**Comment by SaravanaStorageNetwork** [comment]
@yu-yang2  It is explained in the same document.

> NOTE: 2 node clusters are not officially recommended as it causes some known replication issues (split brain), and if possible a 3+ node cluster should be used if possible.

You will find more info. on the same topic here:
http://docs.gluster.org/en/latest/Administrator%20Guide/arbiter-volumes-and-quorum/#split-brains-in-replica-volumes

**Comment by SaravanaStorageNetwork** [comment]
In future, arbiter volume may be supported, where can help to save more space.

> The arbiter volume is a special subset of replica volumes that is aimed at preventing split-brains and providing the same consistency guarantees as a normal replica 3 volume without consuming 3x space.

Third brick only saves the metadata information, not complete data.
Refer here for more info.
http://docs.gluster.org/en/latest/Administrator%20Guide/arbiter-volumes-and-quorum/

**Comment by yu-yang2** [comment]
@SaravanaStorageNetwork , thanks for your explanation, it helps me a lot
