### ISSUE TITLE
Heketi Failed to find a list of pods!!!!!

### ISSUE THREAD

**Issue by Liangming666** [gluster/gluster-kubernetes#398]
I did't us gk-deploy,and I create deploy-heketi.yaml successfully,but when I use this command:

	heketi-cli topology load --json=topology.json

to create devs,it did't work,here is the log in deploy-heketi pod:
![qq 20171124162534](https://user-images.githubusercontent.com/26807536/33201602-3710fdd0-d134-11e7-80d4-2384963a4df4.jpg)

It seemed like it can't get pods which labelselect is glusterfs-node from kubernetes api,and here is the kubernete proxy log:

![qq 20171124162607](https://user-images.githubusercontent.com/26807536/33201648-6890ae82-d134-11e7-866a-d7a3fd877e07.jpg)

Please help me......

**Comment by yu-yang2** [comment]
Why don't you use gk-deploy?

**Comment by Liangming666** [comment]
Just now I used gk-deploy,and the result is same... still can't get list of pods,
my kubernetes version is 1.8.2

**Comment by Liangming666** [comment]
@yu-yang2

**Comment by jarrpa** [comment]
@Liangming666 Is there any way you could copy the actual text of your logs rather than sending photos?

The error I'm seeing is usually indicative of a networking problem within the cluster. Indeed, the fact that I'm seeing those kube-proxy errors would also indicate that. How did you deploy your Kube cluster? Are you running any other application pods on it?

**Comment by Liangming666** [comment]
@jarrpa I didn't running any other application pods on it,my master node ip is 192.168.3.9,kubernetes service ip is10.254.0.1
when i run
curl 192.168.3.9:8080 
it was right,but when i run 10.254.0.1,there is connection refused.

Just now I create a Nginx pod an service to valid is there a network problem,and I think there may be some errors about that.
I use the follow yaml file to create a pod and service
_
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    name: nginx
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
           - containerPort: 8080
_
apiVersion: v1
kind: Service
metadata:
  labels:
    name: nginx-svc
  name: nginx-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001
  type: NodePort
  selector:
    name: nginx

after created,I get pods and found the pod is running on my node2,but when I log node2IP:30001,it refused..then I look up my iptables,here is the log about this nginx:

-A KUBE-NODEPORTS -p tcp -m comment --comment "default/nginx-service:" -m tcp --dport 30001 -j KUBE-MARK-MASQ
-A KUBE-NODEPORTS -p tcp -m comment --comment "default/nginx-service:" -m tcp --dport 30001 -j KUBE-SVC-GKN7Y2BSGW4NJTYL

-A KUBE-SVC-GKN7Y2BSGW4NJTYL -m comment --comment "default/nginx-service:" -j KUBE-SEP-AM5YQGPRLIWO6A4D

-A KUBE-SEP-AM5YQGPRLIWO6A4D -s 10.254.27.3/32 -m comment --comment "default/nginx-service:" -j KUBE-MARK-MASQ
-A KUBE-SEP-AM5YQGPRLIWO6A4D -p tcp -m comment --comment "default/nginx-service:" -m tcp -j DNAT --to-destination 10.254.27.3:8080

10.254.27.3 is the nginx pod ip,it seemed no errors here..

**Comment by Liangming666** [comment]
why it was refused when I run

curl 10.254.27.3:8080

**Comment by Liangming666** [comment]
@jarrpa I didn't run any other application pods on it,my default kubernetes service ip is 10.254.0.1
and the error was caused when the pod GET 10.254.0.1,my master node ip is 192.168.3.9,when i run this
curl 192.168.3.9:8080 or curl 192.168.3.9:6443 it responsed,
but when I run this
curl 10.254.0.1:443 it refused,is there any errors about secure?

to valid is there a network problem,I create a tomcat pod,container port is 8080,and the service port is 8081.nodeport is 30002,all of them was right.

thx for help me..

**Comment by jarrpa** [comment]
@Liangming666 A tomcat pod by itself won't tell you if there's a networking problem within the cluster. You need to deploy a pod that will try to communicate either with other pods or the kubeapi. One way to test this might be to deploy a busybox pod then run `curl http://kubernetes:443` or something like that.

Also, you didn't answer my question. I can't properly help you without more context.

**Comment by Liangming666** [comment]
@jarrpa wow... After I run the tomcat pod,The error disappeared....thx
another question: can I use USB driver as the glusterfs device

**Comment by jarrpa** [comment]
@Liangming666 As long as the GlusterFS pods see them as raw block devices (e.g. `/dev/sdb`) they should work.

Please close this issue if the problem has been resolved to your satisfaction. :)
