### ISSUE TITLE
Unable to start application!

### ISSUE THREAD

**Issue by Liangming666** [gluster/gluster-kubernetes#403]
the heketi pod is unable to start application...

I run kubectl describe pods heketi-596b57d45d-qtz2z,here is the log:

Events:
  Type     Reason                 Age               From               Message
  ----     ------                 ----              ----               -------
  Normal   Scheduled              1m                default-scheduler  Successfully assigned heketi-596b57d45d-qtz2z to node0
  Normal   SuccessfulMountVolume  1m                kubelet, node0     MountVolume.SetUp succeeded for volume "heketi-service-account-token-7m7vk"
  Normal   SuccessfulMountVolume  1m                kubelet, node0     MountVolume.SetUp succeeded for volume "config"
  Normal   SuccessfulMountVolume  1m                kubelet, node0     MountVolume.SetUp succeeded for volume "db"
  Normal   Created                54s (x3 over 1m)  kubelet, node0     Created container
  Normal   Started                54s (x3 over 1m)  kubelet, node0     Started container
  Warning  BackOff                36s (x6 over 1m)  kubelet, node0     Back-off restarting failed container
  Warning  FailedSync             36s (x6 over 1m)  kubelet, node0     Error syncing pod

then I run kubectl logs heketi-596b57d45d-qtz2z -p ,it shows:

Heketi v5.0.0-5-gb005e0f-release-5                                                                                                                                                            
ERROR: Unable to start application    

nothing else,is this not a heketi error?????

**Comment by Liangming666** [comment]
Just now I run gk-deploy again,this time the glusterfs-dameonset is wrong

the glusterd.service in glusterfs-pod of my master node dead, and i don't know why,,, it was all right before

here is the log 

[root@node0 /]# systemctl status glusterd.service
● glusterd.service - GlusterFS, a clustered file-system server
   Loaded: loaded (/usr/lib/systemd/system/glusterd.service; enabled; vendor preset: disabled)
   Active: inactive (dead)

**Comment by Liangming666** [comment]
before I rerun gk-deploy,I found one of my node dosen't have gluster-client,then intall gluster-client,and then I 
restart gk-deploy,then have this error

**Comment by jarrpa** [comment]
@Liangming666 First off, please use `` ``` `` to enclose any text that you are copying from the terminal. I have edited your previous comment as an example. :)

Two things:
* How are you re-running gk-deploy? Are you destroying or cleaning the environment before each run?
* What are the events listed when you run `kubectl describe po` on the GlusterFS pod?
* Check the logs in `/var/log/glusterfs`, primarily `glusterd.log`, to see if you spot any errors near the bottom that may help us dissect this further.

**Comment by Liangming666** [comment]
wo,Thanks for you suggestions,I'm new to this.

Fisrt things:Each time a re-running gk-deploy,I delete everything gk-deploy created such as gluster demeonset , heketi deployment,service-account,service.And I check on my dashboard,Each time I re-running gk-deploy,there is noting left before.

Second things,before my master node's gluster dameonset get bad,kubectl describe pod's log is:
```
Events:
Type Reason Age From Message

Normal Scheduled 1m default-scheduler Successfully assigned heketi-596b57d45d-qtz2z to node0
Normal SuccessfulMountVolume 1m kubelet, node0 MountVolume.SetUp succeeded for volume "heketi-service-account-token-7m7vk"
Normal SuccessfulMountVolume 1m kubelet, node0 MountVolume.SetUp succeeded for volume "config"
Normal SuccessfulMountVolume 1m kubelet, node0 MountVolume.SetUp succeeded for volume "db"
Normal Created 54s (x3 over 1m) kubelet, node0 Created container
Normal Started 54s (x3 over 1m) kubelet, node0 Started container
Warning BackOff 36s (x6 over 1m) kubelet, node0 Back-off restarting failed container
Warning FailedSync 36s (x6 over 1m) kubelet, node0 Error syncing pod
```
there just two warning,and don't konw why,then I run kubectl logs heketi-596b57d45d-qtz2z -p,log is:

```
Heketi v5.0.0-5-gb005e0f-release-5
ERROR: Unable to start application
```

After I re-running gk-deploy,glusterd.service of dameonset glusterfs of my master node daed,In that pod,I run systemctl status glusterd.service,here is log:

```
[root@node0 /]# systemctl status glusterd.service
glusterd.service - GlusterFS, a clustered file-system server
   Loaded: loaded (/usr/lib/systemd/system/glusterd.service; enabled; vendor preset: disabled)
   Active: inactive (dead)
```

Thank you very much,It's late in Wuhan... I'll check that gluster log tomorrow

**Comment by yu-yang2** [comment]
@Liangming666 Can you give me you Wecha? I'm using k8s glusterfs in Changsha, let's keep in touch.
