### ISSUE TITLE
Add a PVC with ReadWriteMany

### ISSUE THREAD

**Issue by alvarosIGZ** [gluster/gluster-kubernetes#408]
Hello,
So I have my GlusterFS deployed in Kubernetes and I have to deploy a document manager app.
It has 2 pods, and both of them should use a glusterfs volume, both writing and reading.
Is there any problem with inconsistences? Can I use a PVC in ReadWriteMany?
I didn't find information about it.

Thanks in advance

**Comment by jarrpa** [comment]
Yup, that is in fact the main mode we operate in. :)

**Comment by jarrpa** [comment]
You can find our supported modes about halfway down this page: https://kubernetes.io/docs/concepts/storage/persistent-volumes/

**Comment by alvarosIGZ** [comment]
You mean in the table with Access Modes?
Thanks!

**Comment by jarrpa** [comment]
Yup! Closing this Issue.
