### ISSUE TITLE
Failed to communicate with deploy-heketi service.

### ISSUE THREAD

**Issue by r-moiseev** [gluster/gluster-kubernetes#412]
`gk-deploy` script fails on check heketi api hello.

And it understandable, because this service has In-cluster endpoint IP.

So the question is, does is it ment to be run outside or inside the cluster?

**Comment by rporres** [comment]
This also happens to me when trying to use the gk-deploy script in kubernetes. Taking into account that there are commands to run `heketi-cli` commands inside `deploy-heketi` pod I don't think this is meant to run inside the cluster so I would say this is a bug. I don't have any experience with OpenShift, but it looks that is meant to work with routes that somehow enable the external access.

I guess the easiest fix would be to use the same approach as it is done with `heketi-cli`: use the deploy-heketi pod to run the `curl` command... At least if we're dealing with kubernetes.

**Comment by rporres** [comment]
PR https://github.com/gluster/gluster-kubernetes/pull/414 contains a fix tested in kubernetes 1.8.2

**Comment by michaelmitchell** [comment]
PR #414 fixed this for me, tested kubernetes 1.8.7

**Comment by jarrpa** [comment]
Good to hear. @r-moiseev if you come back and it still doesn't work for you, feel free to reopen this Issue. :)
