### ISSUE TITLE
ProvisioningFailed  Administrator access required

### ISSUE THREAD

**Issue by superbarne** [gluster/gluster-kubernetes#419]
when i create a pvc i get following error. I created all with gk-deploy, but skipped the object creation:

``` ./gk-deploy -g --admin-key <key> --user-key <key> --no-object -y -v ```

```
Name:          gluster-s3-claim
Namespace:     default
StorageClass:  glusterfs-storage
Status:        Pending
Volume:        
Labels:        gluster-s3=pvc
               glusterfs=s3-pvc
Annotations:   volume.beta.kubernetes.io/storage-class=glusterfs-storage
               volume.beta.kubernetes.io/storage-provisioner=kubernetes.io/glusterfs
Finalizers:    []
Capacity:      
Access Modes:  
Events:
  Type     Reason              Age               From                         Message
  ----     ------              ----              ----                         -------
  Warning  ProvisioningFailed  9s (x2 over 23s)  persistentvolume-controller  Failed to provision volume with StorageClass "glusterfs-storage": create volume error: error creating volume Administrator access required

```

**Comment by rsliotta** [comment]
This needs to be run with sudo

**Comment by superbarne** [comment]
i ran this as a root user

**Comment by rsliotta** [comment]
Hello Barne,

Just to let you know, I had a few issues with this, but I am not part of the team.

So the things the document are missing is this MUST be run from the primary Kubernetes master as sudo.
Second , I found an issue in one of the templates and fixed it.

heketi-deployment.yaml:  The initial spec section.


---

kind: Service

apiVersion: v1

metadata:

  name: heketi

  labels:

    glusterfs: heketi-service

    heketi: service

  annotations:

    description: Exposes Heketi Service

spec:

  selector:

    glusterfs: heketi-pod

  ports:

  - name: heketi

    port: 8080

    targetPort: 8080

    nodePort: 30625

  type: NodePort

---

kind: Deployment

apiVersion: extensions/v1beta1

metadata:

  name: heketi

  labels:

    glusterfs: heketi-deployment

    heketi: deployment

  annotations:

    description: Defines how to deploy Heketi

spec:

  replicas: 1

  template:

    metadata:

      name: heketi

      labels:

        glusterfs: heketi-pod

        heketi: pod

    spec:

      serviceAccountName: heketi-service-account

      containers:

      - image: heketi/heketi:dev

        imagePullPolicy: IfNotPresent

        name: heketi

        env:

        - name: HEKETI_USER_KEY

          value: ${HEKETI_USER_KEY}

        - name: HEKETI_ADMIN_KEY

          value: ${HEKETI_ADMIN_KEY}

        - name: HEKETI_EXECUTOR

          value: ${HEKETI_EXECUTOR}

        - name: HEKETI_FSTAB

          value: ${HEKETI_FSTAB}

        - name: HEKETI_SNAPSHOT_LIMIT

          value: '14'

        - name: HEKETI_KUBE_GLUSTER_DAEMONSET

          value: "y"

        ports:

        - containerPort: 8080

        volumeMounts:

        - name: db

          mountPath: "/var/lib/heketi"

        - name: config

          mountPath: /etc/heketi

        readinessProbe:

          timeoutSeconds: 3

          initialDelaySeconds: 3

          httpGet:

            path: "/hello"

            port: 8080

        livenessProbe:

          timeoutSeconds: 3

          initialDelaySeconds: 30

          httpGet:

            path: "/hello"

            port: 8080

      volumes:

      - name: db

        glusterfs:

          endpoints: heketi-storage-endpoints

          path: heketidbstorage

      - name: config

        secret:

          secretName: heketi-config-secret



Now the real problem I found is that the ./gk-deploy -g --abort  does not do a good cleanup.

I wrote a script to clean up my nodes and clean ALL the replaces required to do it again.  I am happy to send it to you but you cannot just run it in your environment.  It is specific to mine but you can see all the places that need to be cleaned up.  This will also require a REBOOT for sure of every node you tried to install it on.

Best regards,

Bob Liotta
SVP IT Enterprise Architect

CEVA Logistics / 10751 Deerwood Park, Blvd, Jacksonville, FL 32256 / www.cevalogistics.com<http://www.cevalogistics.com>
O: +1 904.928.2322 / E: robert.liotta@cevalogistics.com<mailto:robert.liotta@cevalogistics.com>

Making business flow

**Comment by jarrpa** [comment]
@rsliotta `gk-deploy` does NOT need to be run on the primary master. More correctly, it needs to be run from a machine with a user that has cluster administrative privileges through kubectl.

I do agree that the `--abort` function is currently incomplete. Any help in shoring that up would be appreciated. :) Similarly, I can't tell what you changed in the heketi-deployment spec. Can you point it out explicitly or even submit a PR for it?

@superbarne To your original post, I first find it strange that there is a `gluster-s3-claim` given than you specified `--no-object`, which should have skipped the creation of that PVC. Are you able to create any other PVCs?

**Comment by superbarne** [comment]
i original run this with --no-object, but later decided to try and add a pvc with the provided gluster-s3-claim template but then this error occurred.
I think I've got the problem, my  restuser, for the StorageClass was user not admin.

**Comment by jarrpa** [comment]
@superbarne You shouldn't need to use user admin... did changing it to admin resolve your problem?

**Comment by superbarne** [comment]
yes it did

**Comment by jarrpa** [comment]
Hm, irritating, I'll look into this.

**Comment by jarrpa** [comment]
Can you provide the YAML definitions for your StorageClass and PVC?

**Comment by humblec** [comment]
@superbarne that error clearly indicate that, the volume creation is attempted as a normal user who dont have "admin" privilege, it also confirm heketi authentication is enabled. As first step of troubleshooting I would like to ask "storageclass" yaml file as @jarrpa requested. Also I would like to know whether you have created any "secret" for heketi authentication in your cluster.

`#kubectl get secrets` should tell us.

**Comment by jarrpa** [comment]
@humblec Well, he got it to work already by switching to user `admin`. The dangling question was whether the `admin` user is strictly required. I now believe it is, in which case we should update our documentation. In the case of having auth not configured, is the `restUser` parameter for the StorageClass required?

**Comment by humblec** [comment]
@jarrpa ah.. I missed that comment. If authentication is not configured, we dont need restuser param.

**Comment by jarrpa** [comment]
@humblec Woo! Excellent.

@superbarne if the core issue is resolved, please close this issue.
