### ISSUE TITLE
How do you configure the StorageClass for the vagrant deployment?

### ISSUE THREAD

**Issue by wattsteve** [gluster/gluster-kubernetes#42]
While using the vagrant setup, both @screeley and I are running into the problems encountered with https://github.com/gluster/gluster-kubernetes/issues/24. The GlusterFS provisioner has undergone a lot of changes in Kubernetes lately so the first thing I did was ascertain the version the kubernetes version, which is 1.4.5. 

According to history of the provisioning README at the time 1.4.5 shipped (https://github.com/kubernetes/kubernetes/blob/1d527194656bad6a0f191f9fc6160bf7e931cf09/examples/experimental/persistent-volume-provisioning/README.md) the following storage class and claim should work, but they don't. Any idea @jarrpa @humblec ?

[root@master deploy]# cat gluster-sc.yaml 
apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: glusterfs
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: "http://10.36.0.0:8080"
  restuser: "admin"
  secretNamespace: "default"
  secretName: "heketi-service-account-token-7ne36"

[root@master deploy]# cat gluster-claim.yaml 
{
  "kind": "PersistentVolumeClaim",
  "apiVersion": "v1",
  "metadata": {
    "name": "test-claim",
    "annotations": {
        "volume.beta.kubernetes.io/storage-class": "glusterfs"
    }
  },
  "spec": {
    "accessModes": [
      "ReadWriteMany"
    ],
    "resources": {
      "requests": {
        "storage": "5Gi"
      }
    }
  }
}

**Comment by wattsteve** [comment]
For those with this issue, I was able to use the following Storage Class to get this to work: http://pastebin.com/U6rGwY7d

Note: You'll need to change the restUrl to be whatever the Heketi Server URL to whatever the HEKETI_CLI_SERVER value is, and the restuserkey is the name of the Heketi Secret which you can retrieve using "kubectl get secrets"

**Comment by screeley** [comment]
I think you are looking for the more talented screeley: @screeley44

**Comment by screeley44** [comment]
@jarrpa @humblec @wattsteve - I will address with a few PRs today to help make the readme and a _Hello World_ example
