### ISSUE TITLE
Gluster pods should be able to load certain lvm/device-mapper modules

### ISSUE THREAD

**Issue by nixpanic** [gluster/gluster-kubernetes#440]
There is no guarantee that the `dm_thin_pool`, `dm_mirror` and `dm_snapshot` kernel modules are loaded. Creating volumes with Heketi enablee thin-provisioning for the bricks. This will fail if the device-mapper/lvm modules are not available.

Two solutions are available (that I can think of):

1. add a script like `/etc/sysconfig/modules/*.modules` on the host to load the modules on bootup
2. enable the Gluster pods to load the module if they are missing

Approach 2 looks the most reasonable, and the automatic loading of modules is already standard practice for non-containerized environments. In order to make 2 happen in the most cases, it will be needed to bind-mount `/lib/modules` from the host into the pod. Without this bind-mount, the pod will not be able to run `modprobe` with the right `.ko` files.

See-also: #434 `/etc/sysconfig/modules/*.modules` approach

**Comment by jarrpa** [comment]
I'm also fond of approach 2. This makes it so that the kernel modules aren't loaded at boot if GlusterFS is removed.
