### ISSUE TITLE
Failed to install on CoreOS, Unable to create node: New Node doesn't have glusterd running

### ISSUE THREAD

**Issue by htve** [gluster/gluster-kubernetes#451]
Hi,all
  When I run the script, it prompts me `New Node doesn't have glusterd running`. Can anyone help me?

system: CoreOS 1632.3.0
k8s: v1.9.3  

nodes:
>core@master01 ~ $ sudo kubectl get node
NAME           STATUS    ROLES     AGE       VERSION
172.16.8.101   Ready     <none>    3d        v1.9.3
172.16.8.102   Ready     <none>    3d        v1.9.3
172.16.8.103   Ready     <none>    3d        v1.9.3
172.16.8.104   Ready     <none>    3d        v1.9.3
172.16.8.105   Ready     <none>    3d        v1.9.3
172.16.8.106   Ready     <none>    3d        v1.9.3
172.16.8.107   Ready     <none>    3d        v1.9.3
172.16.8.108   Ready     <none>    3d        v1.9.3
172.16.8.11    Ready     <none>    3d        v1.9.3
172.16.8.12    Ready     <none>    3d        v1.9.3
172.16.8.13    Ready     <none>    3d        v1.9.3

Kernel module by all node:
> core@master01 ~/deploy $ lsmod | grep dm_snapshot
dm_snapshot            45056  0
dm_bufio               28672  3 dm_verity,dm_persistent_data,dm_snapshot
dm_mod                126976  8 dm_mirror,dm_log,dm_bufio,dm_verity,dm_thin_pool,dm_snapshot
core@master01 ~/deploy $ lsmod | grep dm_mirror
dm_mirror              28672  0
dm_region_hash         16384  1 dm_mirror
dm_log                 20480  2 dm_mirror,dm_region_hash
dm_mod                126976  8 dm_mirror,dm_log,dm_bufio,dm_verity,dm_thin_pool,dm_snapshot
core@master01 ~/deploy $ lsmod | grep dm_thin_pool
dm_thin_pool           69632  0
dm_persistent_data     73728  1 dm_thin_pool
dm_bio_prison          16384  1 dm_thin_pool
dm_mod                126976  8 dm_mirror,dm_log,dm_bufio,dm_verity,dm_thin_pool,dm_snapshot
core@master01 ~/deploy $ 

fake block devices:
create script:
>sudo dd if=/dev/zero of=/home/core/glusterimage bs=1G count=25
sudo losetup /dev/loop0 /home/core/glusterimage

>core@master01 ~ $ losetup -a
/dev/loop0: []: (/home/core/glusterimage)

topology.json:
>{
  "clusters": [
  	{
	  "nodes": [
	  	{
	  	  "node": { "hostnames": { "manage": [ "172.16.8.11" ], "storage": [ "172.16.8.11" ] }, "zone": 1 },
	  	  "devices": [ "/dev/loop0" ]
	  	},
	  	{
	  	  "node": { "hostnames": { "manage": [ "172.16.8.12" ], "storage": [ "172.16.8.12" ] }, "zone": 1 },
	  	  "devices": [ "/dev/loop0" ]
	  	},
	  	{
	  	  "node": { "hostnames": { "manage": [ "172.16.8.13" ], "storage": [ "172.16.8.13" ] }, "zone": 1 },
	  	  "devices": [ "/dev/loop0" ]
	  	},
	  	{
	  	  "node": { "hostnames": { "manage": [ "172.16.8.101" ], "storage": [ "172.16.8.101" ] }, "zone": 1 },
	  	  "devices": [ "/dev/loop0" ]
	  	},
	  	{
	  	  "node": { "hostnames": { "manage": [ "172.16.8.102" ], "storage": [ "172.16.8.102" ] }, "zone": 1 },
	  	  "devices": [ "/dev/loop0" ]
	  	},
	  	{
	  	  "node": { "hostnames": { "manage": [ "172.16.8.103" ], "storage": [ "172.16.8.103" ] }, "zone": 1 },
	  	  "devices": [ "/dev/loop0" ]
	  	},
	  	{
	  	  "node": { "hostnames": { "manage": [ "172.16.8.104" ], "storage": [ "172.16.8.104" ] }, "zone": 1 },
	  	  "devices": [ "/dev/loop0" ]
	  	},
	  	{
	  	  "node": { "hostnames": { "manage": [ "172.16.8.105" ], "storage": [ "172.16.8.105" ] }, "zone": 1 },
	  	  "devices": [ "/dev/loop0" ]
	  	},
	  	{
	  	  "node": { "hostnames": { "manage": [ "172.16.8.106" ], "storage": [ "172.16.8.106" ] }, "zone": 1 },
	  	  "devices": [ "/dev/loop0" ]
	  	},
	  	{
	  	  "node": { "hostnames": { "manage": [ "172.16.8.107" ], "storage": [ "172.16.8.107" ] }, "zone": 1 },
	  	  "devices": [ "/dev/loop0" ]
	  	},
	  	{
	  	  "node": { "hostnames": { "manage": [ "172.16.8.108" ], "storage": [ "172.16.8.108" ] }, "zone": 1 },
	  	  "devices": [ "/dev/loop0" ]
	  	}
	  ]
  	}
  ]
}

run:
>sudo ./gk-deploy -g -c kubectl -t ./kube-templates -l ./log.txt -v topology.json

log:
>Using Kubernetes CLI.
Checking status of namespace matching 'default':
default   Active    3d
Using namespace "default".
Checking for pre-existing resources...
  GlusterFS pods ... 
Checking status of pods matching '--selector=glusterfs=pod':
glusterfs-2wrf9   1/1       Running   0         10m
glusterfs-7m82j   1/1       Running   0         10m
glusterfs-8kfl6   1/1       Running   0         10m
glusterfs-bvzw5   1/1       Running   0         10m
glusterfs-fppvb   1/1       Running   0         10m
glusterfs-g6vxh   1/1       Running   0         10m
glusterfs-m2r9k   1/1       Running   0         10m
glusterfs-nbds9   1/1       Running   0         10m
glusterfs-rfrv8   1/1       Running   0         10m
glusterfs-w4xrm   1/1       Running   0         10m
glusterfs-wrj9c   1/1       Running   0         10m
found.
  deploy-heketi pod ... 
Checking status of pods matching '--selector=deploy-heketi=pod':
Timed out waiting for pods matching '--selector=deploy-heketi=pod'.
not found.
  heketi pod ... 
Checking status of pods matching '--selector=heketi=pod':
Timed out waiting for pods matching '--selector=heketi=pod'.
not found.
  gluster-s3 pod ... 
Checking status of pods matching '--selector=glusterfs=s3-pod':
Timed out waiting for pods matching '--selector=glusterfs=s3-pod'.
not found.
Creating initial resources ... kubectl -n default create -f ./kube-templates/heketi-service-account.yaml 2>&1
serviceaccount "heketi-service-account" created
kubectl -n default create clusterrolebinding heketi-sa-view --clusterrole=edit --serviceaccount=default:heketi-service-account 2>&1
clusterrolebinding "heketi-sa-view" created
kubectl -n default label --overwrite clusterrolebinding heketi-sa-view glusterfs=heketi-sa-view heketi=sa-view
clusterrolebinding "heketi-sa-view" labeled
OK
kubectl -n default create secret generic heketi-config-secret --from-file=private_key=/dev/null --from-file=./heketi.json --from-file=topology.json=topology.json
secret "heketi-config-secret" created
kubectl -n default label --overwrite secret heketi-config-secret glusterfs=heketi-config-secret heketi=config-secret
secret "heketi-config-secret" labeled
sed -e 's/\${HEKETI_EXECUTOR}/kubernetes/' -e 's#\${HEKETI_FSTAB}#/var/lib/heketi/fstab#' -e 's/\${HEKETI_ADMIN_KEY}//' -e 's/\${HEKETI_USER_KEY}//' ./kube-templates/deploy-heketi-deployment.yaml | kubectl -n default create -f - 2>&1
service "deploy-heketi" created
deployment "deploy-heketi" created
Waiting for deploy-heketi pod to start ... 
Checking status of pods matching '--selector=deploy-heketi=pod':
deploy-heketi-7c4898d9cd-ggftw   1/1       Running   0         5m
OK
Determining heketi service URL ... OK
kubectl -n default exec -i deploy-heketi-7c4898d9cd-ggftw -- heketi-cli -s http://localhost:8080 --user admin --secret '' topology load --json=/etc/heketi/topology.json 2>&1
Creating cluster ... ID: 7c53c51e27f4db457670f7dc17a6b0c3
Allowing file volumes on cluster.
Allowing block volumes on cluster.
Creating node 172.16.8.11 ... Unable to create node: New Node doesn't have glusterd running
Creating node 172.16.8.12 ... Unable to create node: New Node doesn't have glusterd running
Creating node 172.16.8.13 ... Unable to create node: New Node doesn't have glusterd running
Creating node 172.16.8.101 ... Unable to create node: New Node doesn't have glusterd running
Creating node 172.16.8.102 ... Unable to create node: New Node doesn't have glusterd running
Creating node 172.16.8.103 ... Unable to create node: New Node doesn't have glusterd running
Creating node 172.16.8.104 ... Unable to create node: New Node doesn't have glusterd running
Creating node 172.16.8.105 ... Unable to create node: New Node doesn't have glusterd running
Creating node 172.16.8.106 ... Unable to create node: New Node doesn't have glusterd running
Creating node 172.16.8.107 ... Unable to create node: New Node doesn't have glusterd running
Creating node 172.16.8.108 ... Unable to create node: New Node doesn't have glusterd running
Error loading the cluster topology.
Please check the failed node or device and rerun this script.

**Comment by lucamaro** [comment]
I had the same problem and found this workaround: when gluster is deployed as pod (`-g`) it exposes sshd on port 2222 of node. So you have to specify the option `--ssh-port 2222`. 

If this is correct, I think there is a bug in the gk-deploy script that don't care about this option, here a small patch: 

```
$ git diff
diff --git a/deploy/gk-deploy b/deploy/gk-deploy
index 625961c..f34f0b2 100755
--- a/deploy/gk-deploy
+++ b/deploy/gk-deploy
@@ -676,7 +676,7 @@ if [[ "${EXECUTOR}" == "ssh" ]]; then
     fi
     # shellcheck disable=SC2029
     # I want this parsed client-side
-    ssh "${SSH_USER}@${node}" -q -i "${SSH_KEYFILE}" -C "${sudocmd}gluster volume status" >/dev/null 2>&1
+    ssh "${SSH_USER}@${node}" -q -i "${SSH_KEYFILE}" -p $SSH_PORT -C "${sudocmd}gluster volume status" >/dev/null 2>&1
     if [[ ${?} -ne 0 ]]; then
       output "Can't access glusterd on '${node}'"
       exit 1
```

I needed to copy public key into authorized_keys file of user root in the pod to complete auth... 

I hope all this is an ugly workaround and I'm missing something :)

**Comment by htve** [comment]
@lucamaro
Thank you very much, but I have solved the problem, because I redeploy my cluster, the new cluster does not have this problem, I think, this should be a cluster deployment problem.

**Comment by lucamaro** [comment]
Did you redeploy with gluster server in a pod or server is installed on the node os?
