### ISSUE TITLE
How to get type distributed with no replication?

### ISSUE THREAD

**Issue by grantcurell** [gluster/gluster-kubernetes#453]
I read here: https://kubernetes.io/docs/concepts/storage/storage-classes/#glusterfs

But it frustratingly points to the admin guide [here ](https://access.redhat.com/documentation/en-us/red_hat_gluster_storage/3.1/html/administration_guide/part-overview) which doesn't help at all with determining the syntax of the volumetype for kubernetes. (At least not in any obvious way.)

How can I tell Kubernetes to provision a GlusterFS storage class of type distributed with zero replication? Basically, I want the kubernetes version of `heketi-cli volume create --size=100 --durability=none`

**Comment by jarrpa** [comment]
Apologies for the delay!

The `volumetype` StorageClass parameter is directly analogous to the `durability` parameter. THus setting that to `none` achieves the desired effect.

Closing this issue. Feel free to open it again if my answer is unclear. :)
