### ISSUE TITLE
Unable to create node: New Node doesn't have glusterd running

### ISSUE THREAD

**Issue by yoke88** [gluster/gluster-kubernetes#460]
``` text
[cmdexec] ERROR 2018/04/11 07:08:14 /src/github.com/heketi/heketi/pkg/utils/ssh/ssh.go:170: Failed to run command [/bin/bash -c 'systemctl status glusterd'] on ceph4:22: Err[Process exited with status 3]: Stdout [* glusterd.service
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)
```

but my glusterfs server service name is not glusterd in ubuntu
```bash
systemctl list-units|grep gluster

 run-gluster-shared_storage.mount                                                                        loaded    active mounted   /run/gluster/shared_storage
  glusterfs-server.service                                                                                loaded    active running   LSB: GlusterFS server

```

**Comment by nixpanic** [comment]
This looks like incorrect packaging in Ubuntu. Where did you get the packages from? The [recommended locations are listed in the Install Guide](https://docs.gluster.org/en/latest/Install-Guide/Community_Packages/).

The [glusterfs sources provide a `glusterd.service`](https://github.com/gluster/glusterfs/tree/master/extras/systemd) and not a `glusterfs-server.service`.

**Comment by yoke88** [comment]
after i edit the file /etc/init.d/glusterfs-server, changed the line `# Provides:          glusterfs-server
` to `# Provides:          glusterd`

then `systemctl daemon-reload` 

the glusterd service name changed to glusterd.

``` text

root@ceph2:~# dpkg -la|grep gluster
ii  glusterfs-client                    3.10.11-ubuntu1~xenial1                    amd64        clustered file-system (client package)
ii  glusterfs-common                    3.10.11-ubuntu1~xenial1                    amd64        GlusterFS common libraries and translator modules
ii  glusterfs-server                    3.10.11-ubuntu1~xenial1                    amd64        clustered file-system (server package)

```

**Comment by nixpanic** [comment]
Yes, that is one way to work around the problem. Please report the incorrect service name to the Ubuntu maintainers. They can then decide to rename the `init.d`/`.service` file, or add the `Provides` or `Alias` directives.

Once done, add the link to the report here so that others can find it as well. Thanks!
