### ISSUE TITLE
How do i check how much storage is remaining in my glusterfs cluster?

### ISSUE THREAD

**Issue by Justluckyg** [gluster/gluster-kubernetes#474]
As far as I know the volume claims are redundant into multiple nodes. (atleast 3times redundancy right?) If I provisioned 50gb x 4 partition, that gives me 200gb. But I can  only provision pvc 200/3 correct? Im not sure if this is correct though. I would like to know or find a way to see my available volume/storage that I can claim or extend.

Thanks!

**Comment by jarrpa** [comment]
Hi! Sorry for the delay, I was traveling last week.

You can provision whatever replica count you want. If you're using dynamic provisioning, you would create a StorageClass with the parameter `volumetype: "replicate:n"`, or on the heketi-vli `volume create -replica n` where `n` is the desired number of replicas.

Currently there's no easy way to determine available storage capacity. One thing you could do is run the `pvs` and `vgs` commands on all your Gluster nodes to determine the amount of allocatable space left on the storage devices.

**Comment by Justluckyg** [comment]
Thanks as always @jarrpa That answers my question.
