### ISSUE TITLE
gk-deploy error: cat: /tmp/heketi-storage.json: No such file or directory

### ISSUE THREAD

**Issue by mootezbessifi** [gluster/gluster-kubernetes#475]
Dears,

when i tried to execute gk-deploy on my k8s cluster i get the following error after topology load:

`cat: /tmp/heketi-storage.json: No such file or directory
command terminated with exit code 1
error: no objects passed to create
Failed on creating heketi storage resources.`

any help here !!!

**Comment by mootezbessifi** [comment]
i tried to make some troubleshooting  and i find out that when the gk-deploy script come to execute the below line:
` heketi-cli -s http://localhost:8080 --user admin --secret '' setup-openshift-heketi-storage --listfile=/tmp/heketi-storage.json ' '`

it hang for a while and skip the execution. that's why  /tmp/heketi-storage.json was not created.

what can be the route cause . ?

**Comment by jarrpa** [comment]
Could you have a look at the output of `kubectl logs <heketi_pod>` and see if you can find what commands it failed on?

**Comment by mootezbessifi** [comment]
Hi, the issue was that forgot to load kernel modules, thank you . issue resolved
