### ISSUE TITLE
Give specific name to the created logical volume when dynamically creating a k8s pvc

### ISSUE THREAD

**Issue by mootezbessifi** [gluster/gluster-kubernetes#477]
I am trying to deal with dynamic storage provisioning in kubernetes using pvc and gluster storage class. when i try to create a pvc it creates to me an LV (logical volume) with a random name (brick_xxxxxxxx) and bind it to the k8s pv.

In case when i am provisioning too many volumes, it will be very difficult to know which created LV belongs to which k8s pvc.

My question is, is there any way or parameter to give to the k8s pvc in such a way that the value will be the name of the created lv ??

**Comment by jarrpa** [comment]
Sorry for the delay, hope this still reaches you.

The GlusterFS provisioner now takes a new [`volumeprefix` parameter](https://github.com/kubernetes/examples/tree/master/staging/persistent-volume-provisioning#glusterfs), which would allow you to easily identify which volumes map to which PV/PVC pairs. Unfortunately, this won't affect the brick names and you'll have to resolve to using either `heketi-cli volume info` or `glusterfs volume status` to get the volume <-> brick mapping.

As there are no plans to change this any time soon, I'm closing this Issue. If you still feel strongly about this, please open an Issue against the heketi project.
