### ISSUE TITLE
Error: Unable to parse config file (exit code 255)

### ISSUE THREAD

**Issue by letavia** [gluster/gluster-kubernetes#482]
Hello!

I ran into problem running gk-deploy.

Error: Unable to parse config file
command terminated with exit code 255
Error loading the cluster topology.
Please check the failed node or device and rerun this script.

When I checked with "kubectl get all" all resources are running well. Everything also seemed fine when I ran "kubectl describe deploy-heketi-xxxxx-xxxxx".
Only when running "kubectl logs deploy-heketi-xxxxx-xxxxx" here is what I got:

Setting up heketi database
No database file found
stat: cannot stat '/var/lib/heketi/heketi.db': No such file or directory
Heketi v6.0.0-196-gf31ad28
[heketi] INFO 2018/06/05 13:15:04 Loaded kubernetes executor
[heketi] INFO 2018/06/05 13:15:04 GlusterFS Application Loaded
[heketi] INFO 2018/06/05 13:15:04 Started Node Health Cache Monitor
Listening on port 8080
[heketi] INFO 2018/06/05 13:15:14 Starting Node Health Status refresh
[heketi] INFO 2018/06/05 13:15:14 Cleaned 0 nodes from health cache
[heketi] INFO 2018/06/05 13:17:04 Starting Node Health Status refresh
[heketi] INFO 2018/06/05 13:17:04 Cleaned 0 nodes from health cache

Is it because there's no secret for heketi db? gk-deploy does not create the secret for the db. I tried to create it manually with command line but to no avail.

Tried running gk-deploy -g --abort

Using Kubernetes CLI.
Using namespace "default".
Do you wish to abort the deployment?
[Y]es, [N]o? [Default: N]: Y
deployment "deploy-heketi" deleted
pod "deploy-heketi-6c7d48f8b-dt6lv" deleted
service "deploy-heketi" deleted
secret "heketi-config-secret" deleted
serviceaccount "heketi-service-account" deleted
clusterrolebinding "heketi-sa-view" deleted
Error from server (NotFound): services "heketi-storage-endpoints" not found
No resources found
node "gke-kubecity-default-pool-68c3f103-j0vk" labeled
node "gke-kubecity-default-pool-68c3f103-mmj7" labeled
node "gke-kubecity-default-pool-68c3f103-zdn4" labeled
daemonset "glusterfs" deleted

And ./gk-deploy -gv
Welcome to the deployment tool for GlusterFS on Kubernetes and OpenShift.

Before getting started, this script has some requirements of the execution
environment and of the container platform that you should verify.

The client machine that will run this script must have:
 * Administrative access to an existing Kubernetes or OpenShift cluster
 * Access to a python interpreter 'python'

Each of the nodes that will host GlusterFS must also have appropriate firewall
rules for the required GlusterFS ports:
 * 2222  - sshd (if running GlusterFS in a pod)
 * 24007 - GlusterFS Management
 * 24008 - GlusterFS RDMA
 * 49152 to 49251 - Each brick for every volume on the host requires its own
   port. For every new brick, one new port will be used starting at 49152. We
   recommend a default range of 49152-49251 on each host, though you can adjust
   this to fit your needs.

The following kernel modules must be loaded:
 * dm_snapshot
 * dm_mirror
 * dm_thin_pool

For systems with SELinux, the following settings need to be considered:
 * virt_sandbox_use_fusefs should be enabled on each node to allow writing to
   remote GlusterFS volumes

In addition, for an OpenShift deployment you must:
 * Have 'cluster_admin' role on the administrative account doing the deployment
 * Add the 'default' and 'router' Service Accounts to the 'privileged' SCC
 * Have a router deployed that is configured to allow apps to access services
   running in the cluster

Do you wish to proceed with deployment?

[Y]es, [N]o? [Default: Y]:
Using Kubernetes CLI.

Checking status of namespace matching 'default':
default   Active    2d
Using namespace "default".
Checking for pre-existing resources...
  GlusterFS pods ...
Checking status of pods matching '--selector=glusterfs=pod':

Timed out waiting for pods matching '--selector=glusterfs=pod'.
not found.
  deploy-heketi pod ...
Checking status of pods matching '--selector=deploy-heketi=pod':

Timed out waiting for pods matching '--selector=deploy-heketi=pod'.
not found.
  heketi pod ...
Checking status of pods matching '--selector=heketi=pod':

Timed out waiting for pods matching '--selector=heketi=pod'.
not found.
  gluster-s3 pod ...
Checking status of pods matching '--selector=glusterfs=s3-pod':

Timed out waiting for pods matching '--selector=glusterfs=s3-pod'.
not found.
Creating initial resources ... /google/google-cloud-sdk/bin/kubectl -n default create -f /home/kube/gluster-kubernetes/deploy/kube-templates/heketi-service-account.yaml 2>&1
serviceaccount "heketi-service-account" created
/google/google-cloud-sdk/bin/kubectl -n default create clusterrolebinding heketi-sa-view --clusterrole=edit --serviceaccount=default:heketi-service-account 2>&1
clusterrolebinding "heketi-sa-view" created
/google/google-cloud-sdk/bin/kubectl -n default label --overwrite clusterrolebinding heketi-sa-view glusterfs=heketi-sa-view heketi=sa-view
clusterrolebinding "heketi-sa-view" labeled
OK
Marking 'gke-kubecity-default-pool-68c3f103-j0vk' as a GlusterFS node.
/google/google-cloud-sdk/bin/kubectl -n default label nodes gke-kubecity-default-pool-68c3f103-j0vk storagenode=glusterfs --overwrite 2>&1
node "gke-kubecity-default-pool-68c3f103-j0vk" labeled
Marking 'gke-kubecity-default-pool-68c3f103-mmj7' as a GlusterFS node.
/google/google-cloud-sdk/bin/kubectl -n default label nodes gke-kubecity-default-pool-68c3f103-mmj7 storagenode=glusterfs --overwrite 2>&1
node "gke-kubecity-default-pool-68c3f103-mmj7" labeled
Marking 'gke-kubecity-default-pool-68c3f103-zdn4' as a GlusterFS node.
/google/google-cloud-sdk/bin/kubectl -n default label nodes gke-kubecity-default-pool-68c3f103-zdn4 storagenode=glusterfs --overwrite 2>&1
node "gke-kubecity-default-pool-68c3f103-zdn4" labeled
Deploying GlusterFS pods.
sed -e 's/storagenode\: glusterfs/storagenode\: 'glusterfs'/g' /home/kube/gluster-kubernetes/deploy/kube-templates/glusterfs-daemonset.yaml | /google/google-cloud-sdk/bin/kubectl -n default create -f - 2>&1
daemonset "glusterfs" created
Waiting for GlusterFS pods to start ...
Checking status of pods matching '--selector=glusterfs=pod':
glusterfs-68dcg   1/1       Running   0         1m
glusterfs-7dw5j   1/1       Running   0         1m
glusterfs-m9vpq   1/1       Running   0         1m
OK
/google/google-cloud-sdk/bin/kubectl -n default create secret generic heketi-config-secret --from-file=private_key=/dev/null --from-file=./heketi.json --from-file=topology.json=topology.json
secret "heketi-config-secret" created
/google/google-cloud-sdk/bin/kubectl -n default label --overwrite secret heketi-config-secret glusterfs=heketi-config-secret heketi=config-secret
secret "heketi-config-secret" labeled
sed -e 's/\${HEKETI_EXECUTOR}/kubernetes/' -e 's#\${HEKETI_FSTAB}#/var/lib/heketi/fstab#' -e 's/\${HEKETI_ADMIN_KEY}//' -e 's/\${HEKETI_USER_KEY}//' /home/kube/gluster-kubernetes/deploy/kube-templates/deploy-heketi-deployment.yaml | /google/google-cloud-sdk/bin/kubectl -n default create -f - 2>&1
service "deploy-heketi" created
deployment "deploy-heketi" created
Waiting for deploy-heketi pod to start ...
Checking status of pods matching '--selector=deploy-heketi=pod':
deploy-heketi-6c7d48f8b-dt6lv   1/1       Running   0         9s
OK
Determining heketi service URL ... OK
/google/google-cloud-sdk/bin/kubectl -n default exec -i deploy-heketi-6c7d48f8b-dt6lv -- heketi-cli -s http://localhost:8080 --user admin --secret '' topology load --json=/etc/heke
ti/topology.json 2>&1
Error: Unable to parse config file
command terminated with exit code 255
Error loading the cluster topology.
Please check the failed node or device and rerun this script.

I have a Kubernetes cluster on gke with three nodes. I ran wipefs on the nodes but did not format the unmounted disks to xfs format. 
Any help is more than appreciated.

**Comment by jarrpa** [comment]
You probably have an error in your topology file, a missing comma or something. If you don't see anything immediately paste it here (between `` ``` ``).

**Comment by letavia** [comment]
My topology was fine. The problem was I missed the pre-requisites. After I did all the pre-requisites the deployment worked like a charm.
