### ISSUE TITLE
pvcreate may trigger an interactive dialog if partition table exists

### ISSUE THREAD

**Issue by lulf** [gluster/gluster-kubernetes#497]
As a first timer setting up gluster-kubernetes on OpenShift (using the ansible playbooks but AFAICT this project is used as a base), i encountered an issue that was very hard to debug for a newbie like myself. Loading the topology would take forever and never finish, glusterd logs looked fine, though I'm wasn't sure what fine was supposed to look like, but nothing stood out.

By accident I saw that there was a pvcreate process on the node hanging, and it turned out it was hanging in an interactive dialog asking if the existing partition table should be cleared, which I discovered after running the command myself.

Although I take full responsibility of not having clean disks to begin with, having a check in the setup phase to verify that the pvcreate would pass, or modify pvcreate command to not be interactive would be an improvement for someone installing and not knowing what to look for.

**Comment by nixpanic** [comment]
We added an option to wipe all data on the disks with heketi/heketi#1185. You can set the dangerous `destroydata` option for each of the block devices in your `topology.json` as shown in [this example](https://github.com/heketi/heketi/blob/master/client/cli/go/topology-sample.json) in the heketi repo.

heketi/heketi#1247 adds the `-qq` option to `pvremove` and similar. This causes it to skip the prompt and fail immediately. Maybe we should add it to `pvcreate` too.

Do you want to send a PR for adding the `destroydata` option in the [topology.json.sample](https://github.com/gluster/gluster-kubernetes/blob/master/deploy/topology.json.sample) of this repo?

**Comment by lulf** [comment]
Having -qq for pvcreate I think is a good fix. Just getting some response immediately is much better than nothing.

I might send a PR though I will be away for the next month, so don't wait for it :)
