### ISSUE TITLE
The --abort function acts differently with -g option.

### ISSUE THREAD

**Issue by humblec** [gluster/gluster-kubernetes#51]

**Comment by jarrpa** [comment]
...yes? This is intentional so as to allow `gk-deploy` to delete the GlusterFS pods if they were improperly created.

**Comment by MohamedAshiqrh** [comment]
@jarrpa so the situation we faced is when we are deploying everything and it fails. abort was called without ${GLUSTER}=1. I am not sure why. so abort will always have ${GLUSTER}=1 when it is internally called is it.

**Comment by MohamedAshiqrh** [comment]
@jarrpa I mean when we do gk-deploy -g

**Comment by jarrpa** [comment]
I'm still not sure I understand the problem. When you call `gk-deploy --abort -g` you will always have `GLUSTER=1`, and thus it will try to take down any existing GlusterFS pods and related resources. if you don't specify `-g` with `--abort` then it won't try to do that, as no state is persisted between calls of `gk-deploy`. What am I missing?

**Comment by MohamedAshiqrh** [comment]
@jarrpa You are not missing anything. We thought there was a issue when we did it. I now understand it. We can close this issue. As it was just a confusion.

**Comment by jarrpa** [comment]
Ah, whew. No worries! :)
