### ISSUE TITLE
gk-deploy fails waiting for pods matching '--selector=glusterfs=pod'

### ISSUE THREAD

**Issue by sgmacdougall** [gluster/gluster-kubernetes#510]
When running gk-deploy it gets to the point where it deploys the glusterfs pods, then it waits for a few minutes before it times out, even though the pods are running. Here's the output from 'gk-deploy -gvy'.

Using Kubernetes CLI.

Checking status of namespace matching 'default':
default   Active    76d
Using namespace "default".
Checking for pre-existing resources...
  GlusterFS pods ... 
Checking status of pods matching '--selector=glusterfs=pod':

Timed out waiting for pods matching '--selector=glusterfs=pod'.
not found.
  deploy-heketi pod ... 
Checking status of pods matching '--selector=deploy-heketi=pod':

Timed out waiting for pods matching '--selector=deploy-heketi=pod'.
not found.
  heketi pod ... 
Checking status of pods matching '--selector=heketi=pod':

Timed out waiting for pods matching '--selector=heketi=pod'.
not found.
  gluster-s3 pod ... 
Checking status of pods matching '--selector=glusterfs=s3-pod':

Timed out waiting for pods matching '--selector=glusterfs=s3-pod'.
not found.
Creating initial resources ... /usr/bin/kubectl -n default create -f /home/steve/kubernetes/elk/kube-templates/heketi-service-account.yaml 2>&1
serviceaccount/heketi-service-account created
/usr/bin/kubectl -n default create clusterrolebinding heketi-sa-view --clusterrole=edit --serviceaccount=default:heketi-service-account 2>&1
clusterrolebinding.rbac.authorization.k8s.io/heketi-sa-view created
/usr/bin/kubectl -n default label --overwrite clusterrolebinding heketi-sa-view glusterfs=heketi-sa-view heketi=sa-view
clusterrolebinding.rbac.authorization.k8s.io/heketi-sa-view labeled
OK
Marking '10.180.11.194' as a GlusterFS node.
/usr/bin/kubectl -n default label nodes 10.180.11.194 storagenode=glusterfs --overwrite 2>&1
node/10.180.11.194 not labeled
Marking '10.180.11.195' as a GlusterFS node.
/usr/bin/kubectl -n default label nodes 10.180.11.195 storagenode=glusterfs --overwrite 2>&1
node/10.180.11.195 not labeled
Marking '10.180.11.196' as a GlusterFS node.
/usr/bin/kubectl -n default label nodes 10.180.11.196 storagenode=glusterfs --overwrite 2>&1
node/10.180.11.196 not labeled
Deploying GlusterFS pods.
sed -e 's/storagenode\: glusterfs/storagenode\: 'glusterfs'/g' /home/steve/kubernetes/elk/kube-templates/glusterfs-daemonset.yaml | /usr/bin/kubectl -n default create -f - 2>&1
daemonset.extensions/glusterfs created
Waiting for GlusterFS pods to start ... 
Checking status of pods matching '--selector=glusterfs=pod':
glusterfs-kz2zc   0/1       Running   0         6m
glusterfs-tj6qx   0/1       Running   0         6m
glusterfs-zkg59   0/1       Running   0         6m
Timed out waiting for pods matching '--selector=glusterfs=pod'.
pods not found.

**Comment by sgmacdougall** [comment]
I deleted the glusterfs daemonset and tried gk-deploy again, similar result:

daemonset.extensions/glusterfs created
Waiting for GlusterFS pods to start ... 
Checking status of pods matching '--selector=glusterfs=pod':
glusterfs-dxfdf   0/1       Running   0         3m
glusterfs-l5bq9   0/1       Running   0         3m
glusterfs-p6982   0/1       Running   0         3m

When I look at syslog I see this:
Aug 23 16:29:42 10 containerd[1294]: time="2018-08-23T16:29:42-04:00" level=info msg="ExecSync for "fecf862c4ae2792b71035876f2f20043224e68b3925fc54a48a1ff3ffdcc0ed4" with command [/bin/bash -c systemctl status glusterd.service] and timeout 3 (s)"
Aug 23 16:29:42 10 containerd[1294]: time="2018-08-23T16:29:42-04:00" level=info msg="Finish piping "stdout" of container exec "a86c2d811ec8f50dcc1032825d35865c56400224034bb21a9410d5287ca54262""
Aug 23 16:29:42 10 containerd[1294]: time="2018-08-23T16:29:42-04:00" level=info msg="Finish piping "stderr" of container exec "a86c2d811ec8f50dcc1032825d35865c56400224034bb21a9410d5287ca54262""
Aug 23 16:29:42 10 containerd[1294]: time="2018-08-23T16:29:42-04:00" level=info msg="Exec process "a86c2d811ec8f50dcc1032825d35865c56400224034bb21a9410d5287ca54262" exits with exit code 3 and error <nil>"
Aug 23 16:29:42 10 containerd[1294]: time="2018-08-23T16:29:42-04:00" level=info msg="ExecSync for "fecf862c4ae2792b71035876f2f20043224e68b3925fc54a48a1ff3ffdcc0ed4" returns with exit code 3"
Aug 23 16:29:42 10 kubelet[1491]: I0823 16:29:42.335434    1491 prober.go:111] Liveness probe for "glusterfs-dxfdf_default(fdba7974-a712-11e8-9696-005056aa3804):glusterfs" failed (failure): ● glusterd.service - GlusterFS, a clustered file-system server
Aug 23 16:29:42 10 kubelet[1491]:    Loaded: loaded (/usr/lib/systemd/system/glusterd.service; enabled; vendor preset: disabled)
Aug 23 16:29:42 10 kubelet[1491]:    Active: failed (Result: exit-code) since Thu 2018-08-23 20:27:45 UTC; 1min 56s ago
Aug 23 16:29:42 10 kubelet[1491]:   Process: 67 ExecStart=/usr/sbin/glusterd -p /var/run/glusterd.pid --log-level $LOG_LEVEL $GLUSTERD_OPTIONS (code=exited, status=1/FAILURE)
Aug 23 16:29:42 10 kubelet[1491]: Aug 23 20:27:45 10.180.11.194 systemd[1]: Starting GlusterFS, a clustered file-system server...
Aug 23 16:29:42 10 kubelet[1491]: Aug 23 20:27:45 10.180.11.194 systemd[1]: glusterd.service: control process exited, code=exited status=1
Aug 23 16:29:42 10 kubelet[1491]: Aug 23 20:27:45 10.180.11.194 systemd[1]: Failed to start GlusterFS, a clustered file-system server.
Aug 23 16:29:42 10 kubelet[1491]: Aug 23 20:27:45 10.180.11.194 systemd[1]: Unit glusterd.service entered failed state.
Aug 23 16:29:42 10 kubelet[1491]: Aug 23 20:27:45 10.180.11.194 systemd[1]: glusterd.service failed.

**Comment by phlogistonjohn** [comment]
Since glusterd doesn't seem to be reporting error conditions in the journal snippet you get in systemctl status I recommend looking into the glusterd logs for more information. The gluster pod mounts /var/log/glusterfs from the host, so even when the pod exits there ought to be glusterd logs in the dir.

**Comment by sgmacdougall** [comment]
So even though the pods appear running, the status of the gluserd service on the node is 'failed', near as I can tell it fails to start because of this:

 [glusterfsd.c:2150:parse_cmdline] 0-glusterfs: ERROR: parsing the volfile failed [No such file or directory] 

but I cant figure out how to correct this. Is it telling me it can't find the vol file, or that it can't find the directory to which the vol file refers? My topology file looks like this:


{
  "clusters": [
    {
      "nodes": [
        {
          "node": {
            "hostnames": {
              "manage": [
                "node0"
              ],
              "storage": [
                "10.180.11.194"
              ]
            },
            "zone": 1
          },
          "devices": [
            "/dev/sdc",
            "/dev/sdd"
          ]
        },
        {
          "node": {
            "hostnames": {
              "manage": [
                "node1"
              ],
              "storage": [
                "10.180.11.195"
              ]
            },
            "zone": 1
          },
          "devices": [
            "/dev/sdc",
            "/dev/sdd"
          ]
        },
        {
          "node": {
            "hostnames": {
              "manage": [
                "node2"
              ],
              "storage": [
                "10.180.11.196"
              ]
            },
            "zone": 1
          },
          "devices": [
            "/dev/sdc",
            "/dev/sdd"
          ]
        }
      ]
    }
  ]
}

I've confirmed that /dev/sdc and sdd exist on each node, the IP addresses above are the IP addresses of nodes. Is there something I'm missing in the topology or one of the template files that's causing this volfile error? I'm running 'gk-deploy -gvy' and I've also tried --no-object

**Comment by sgmacdougall** [comment]
Well I managed to get this deployed. I ran 'gk-deploy --abort' and deleted the daemonset, then I deleted:

/var/lib/heketi
/etc/glusterfs
/var/lib/glusterd
/var/lib/misc/glusterfsd

and ran 'gk-deploy -gvy' again. This time it worked. From other forums I think that deleting /var/lib/glusterd was the key. This may have had left over cruft from a previous standalone glusterfs-server installation.
