### ISSUE TITLE
-l && --abort together gives unexpected result.

### ISSUE THREAD

**Issue by humblec** [gluster/gluster-kubernetes#52]
These variables has to be properly parsed and acted.

**Comment by jarrpa** [comment]
Can you describe the issue in more detail before submitting a PR?

**Comment by MohamedAshiqrh** [comment]
-l should have a validation to check and return the argument passed to it is not a flag.

**Comment by jarrpa** [comment]
Ah, yes, makes sense. I would suggest adding it to the [assign function](https://github.com/gluster/gluster-kubernetes/blob/master/deploy/gk-deploy#L119), with a little refactoring so we only have to make the check (see if it starts with `-`) once.

**Comment by jarrpa** [comment]
Currently resolved in the assign() function.
