### ISSUE TITLE
Heketi: Unable to open database: timeout

### ISSUE THREAD

**Issue by Webgardener** [gluster/gluster-kubernetes#531]
Hi,

When trying to export the heketi.db in json format I enconter the following error: 

```
[root@heketi-5bd5d976b6-vvdjg heketi]# heketi db export --dbfile heketi.db --jsonfile /tmp/q.json
[heketi] ERROR 2018/11/05 11:02:19 /src/github.com/heketi/heketi/apps/glusterfs/dbcommon.go:189: Unable to open database: timeout
failed to dump db: Unable to open database: timeout
```

Heketi version: Heketi v8.0.0-1-g082b556-release-8

Thanks in advance,
Thomas

**Comment by Webgardener** [comment]
I might have found an explanation : it seems that it is impossible to open the db if it was already opened by another process (https://github.com/boltdb/bolt#opening-a-database).

**Comment by phlogistonjohn** [comment]
Hi @Webgardener it may be that you haven't stopped a previous running heketi process (heketi pod). This command can only be run if there are no other processes using the db.
There are generally two ways to accessing the heketi db file when the heketi pod is stopped (and the pod does not exist for you to exec commands in):
1. Use glusterfs to mount the `heketidbstorage` volume on another host. One convient place for this is within one of the gluster pods. If using this method it may be useful to copy the `heketi` binary into the root of the heketidbstorage volme first (before stopping it, within the pod, run: cp /usr/bin/heketi /var/lib/heketi).
2. After you stop the heketi pod, create a k8s job or pod manually that uses the same image and mountpoints as the heketi dc but does not start the heketi server. Then you can exec into this pod and run commands like you would the heketi pod without the heketi server process accessing the db.

**Comment by Webgardener** [comment]
The gluster volumes are full... That is why creation of PVC were failing.
