### ISSUE TITLE
Unable to create gluster cluster due to unwritable host /usr/lib

### ISSUE THREAD

**Issue by ofanged1** [gluster/gluster-kubernetes#537]
I am using an existing kubernetes cluster. Added a topology.json that matches my layout.

When I create a new gluster/heketi cluster I receive the error message "Error: failed to start container "glusterfs": Error response from daemon: error while creating mount source path '/usr/lib/modules': mkdir /usr/lib/modules: read-only file system" in my pods.

[According to the template](https://github.com/gluster/gluster-kubernetes/blob/e50a62cda8cda155893afbd124bd9b17602ae471/deploy/kube-templates/glusterfs-daemonset.yaml#L62) this path should be mounted read-only, but it does not exist on my nodes.

But when I attempt to create the path manually, the device this is mounted on is not writable (this folder also does not exist, so it would be empty even if it was a writable filesystem).

```
$ sudo mkdir /usr/lib/modules
mkdir: cannot create directory ‘/usr/lib/modules’: Read-only file system
```

Is it possible to move this path to a different host location? I tried to discern its purpose [from the image's source](https://github.com/gluster/gluster-containers), but couldn't find its relevance.

**Comment by nixpanic** [comment]
The `/usr/lib/modules` directory is needed so that the processes in the glusterfs pod can load kernel modules. Could you check where your host has the modules available? A command like this would show the full path to the fuse module:

    $ modinfo --filename fuse
    /lib/modules/4.18.18-300.fc29.x86_64/kernel/fs/fuse/fuse.ko.xz

What distribution are you using?

**Comment by ofanged1** [comment]
/lib/modules/4.4.111+/kernel/fs/fuse/fuse.ko
Container-Optimized OS

**Comment by nixpanic** [comment]
In that case, you should be able to change the path `/usr/lib/modules` to `/lib/modules` in [`deploy/kube-templates/glusterfs-daemonset.yaml`](https://github.com/gluster/gluster-kubernetes/blob/master/deploy/kube-templates/glusterfs-daemonset.yaml).

This should work on most distributions as `/usr/lib/modules` is the new location for many, but they do provide `/lib` as a symlink to `/usr/lib`.

**Comment by ofanged1** [comment]
Thank you very much for your help, Niels
