### ISSUE TITLE
Too many "resource not found" errors in the screen.

### ISSUE THREAD

**Issue by humblec** [gluster/gluster-kubernetes#54]

**Comment by humblec** [comment]
~~~
No resources found.
No resources found.
No resources found.
No resources found.
No resources found.
No resources found.
No resources found.
No resources found.
No resources found.
No resources found.
No resources found.
No resources found.
No resources found.
No resources found.
No resources found.
No resources found.
No resources found.
~~~

Need to be a `progress bar with dots ` or so..

**Comment by jarrpa** [comment]
Is this even when you don't specify `-v`? If so then yes, that's a major bug. They should just be silenced.

**Comment by MohamedAshiqrh** [comment]
@jarrpa yeah It was in -v even that we can clean by adding "." in place of same output.

**Comment by MohamedAshiqrh** [comment]
@jarrpa I am able to see these without -v.

**Comment by MohamedAshiqrh** [comment]
```
# ashiq=$(oc get pod --no-headers --show-all --selector=glusterfs)
No resources found.

```

**Comment by MohamedAshiqrh** [comment]
I saw if there are some subprocess or extra exec add to handle stdout, I couldn't find any. Then I ran 

# ashiq=$(oc get pod --no-headers --show-all --selector=glusterfs)
No resources found.

I had no gluster pod yet this was wrong as it shouldn't be printing it. I had router running. 

# ashiq=$(oc get pod --no-headers --show-all --selector=router)
# echo $ashiq
aplo-router-1-at7tf 1/1 Running 2 1h

So if there are errors(or no resources) it is showing the output.

# ashiq=$(oc get pod --no-headers --show-all --selector=glusterfs 2>&1)
I pointed stderr to stdout and then it is working fine.

# echo $ashiq
No resources found.

This was the issue it is going to stderr.

**Comment by MohamedAshiqrh** [comment]
Even in verbose it is too bad to fill up the screen with any same state. so added a dotit parameter to debug which will just add a dot in case of same pod state.
