### ISSUE TITLE
Good to have a prereq() function which mention the prerequistes of this tool.

### ISSUE THREAD

**Issue by humblec** [gluster/gluster-kubernetes#56]
Its good to have a function which mention the prerequisites we need to have for the `gk-deploy` to run.  This helps the storage admin wrt to the deployment of this solution.

**Comment by obnoxxx** [comment]
Mention or check?... @humblec 
I think these would be 2 different issues.

**Comment by humblec** [comment]
@obnoxxx ok.. lets have this issue for "mention" and will open another one for "check" later. :)

**Comment by obnoxxx** [comment]
@humblec ACK, thanks.
