### ISSUE TITLE
Prevent volume creation when heketi pod is deleted

### ISSUE THREAD

**Issue by Webgardener** [gluster/gluster-kubernetes#573]
Hello. 
I noticed that deleting the heketi pod while somes PVCs are Pending  leads to heketi.db inconsistency. Repairing the heketi.db is possible but time consuming and prone to errors.

Looking for a way to prevent this to happen...
Maybe by introducing a pre stop lifecycle hook in the heketi deployment so that I can put the heketi server in read-only mode ? 

Ideas welcomed here :)

**Comment by nixpanic** [comment]
This is probably something that could be explained in the heketi documentation. Maybe you want to move the conversation to the [heketi project](https://github.com/heketi/heketi)?

/cc @phlogistonjohn
