### ISSUE TITLE
Add new gluster node failed

### ISSUE THREAD

**Issue by bakonyip** [gluster/gluster-kubernetes#584]
Hi,
I will add new glusterfs node to cluster. I write this command to heketi pod in kubernetes:
heketi-cli topology load --json=topology.json
And new node is say: Unable to create node: peer probe: failed: Probe returned with Transport endpoint is not connected
Firewall is off all host node!
Please help me.
Thanks, Peter

**Comment by danielyeap** [comment]
I am facing the same error while running "gk-deploy".

Did you manage to resolve the problem?
