### ISSUE TITLE
deploy glusterfs fail

### ISSUE THREAD

**Issue by xujingbin** [gluster/gluster-kubernetes#590]
./gk-deploy -gvy

Determining heketi service URL ... OK
/bin/kubectl -n default exec -i deploy-heketi-865f55765-2j6qh -- heketi-cli -s http://localhost:8080 --user admin --secret '' topology load --json=/etc/heketi/topology.json 2>&1
Found node k8s213 on cluster d335d724802283e6f22cf3acce6ae996
Found device /dev/sdb
Found node k8s174 on cluster d335d724802283e6f22cf3acce6ae996
Found device /dev/sdb
Found node k8s52 on cluster d335d724802283e6f22cf3acce6ae996
Adding device /dev/sdb ... Unable to add device: Setup of device /dev/sdb failed (already initialized or contains data?):   WARNING: Device /dev/sdb not initialized in udev database even after waiting 10000000 microseconds.
WARNING: Device /dev/sda2 not initialized in udev database even after waiting 10000000 microseconds.
WARNING: Device /dev/sda3 not initialized in udev database even after waiting 10000000 microseconds.
WARNING: Device /dev/vg_5d5e600579ef3ca89250289215289508/brick_44f35f61d155a4c2e0f94106a9b43b35 not initialized in udev database even after waiting 10000000 microseconds.
WARNING: Device /dev/sda5 not initialized in udev database even after waiting 10000000 microseconds.
WARNING: Device /dev/sda6 not initialized in udev database even after waiting 10000000 microseconds.
WARNING: Device /dev/sdb not initialized in udev database even after waiting 10000000 microseconds.
Can't open /dev/sdb exclusively.  Mounted filesystem?
Can't open /dev/sdb exclusively.  Mounted filesystem?
Error loading the cluster topology.
Please check the failed node or device and rerun this script.

node k8s52
![image](https://user-images.githubusercontent.com/22829724/57762000-3eaae200-7731-11e9-82da-8cf70143912b.png)

what should I do？

**Comment by MFrancesco** [comment]
Having exactly same issue, how did you solve this?

**Comment by whymatter** [comment]
Wipe the device completely

`wipefs -a /dev/sdx`

Make sure you are wiping the correct device...

**Comment by bor8** [comment]
In addition to one above: https://askubuntu.com/a/1028117/519948
