### ISSUE TITLE
discussion: convert json to yaml

### ISSUE THREAD

**Issue by screeley44** [gluster/gluster-kubernetes#64]
Wondering if we should convert json to yaml, I believe OpenShift and Kube have settled on yaml as the official object spec def.

What say you @obnoxxx @jarrpa @wattsteve @erinboyd

I can do the conversion if everyone is in agreement

**Comment by jarrpa** [comment]
@screeley44 I've been wondering why we're using JSON for a while now. I'd love to have them as YAML, that way I'd need to remember fewer curly braces and commas. :)

**Comment by screeley44** [comment]
ok, I'll do the conversion next week and throw it into a PR for your review

**Comment by wattsteve** [comment]
+1 for YAML
